In [1]:
from PIL import Image
import os, glob
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
from keras.models import Sequential
from keras.layers import Convolution2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
import numpy as np

Using TensorFlow backend.


In [3]:
caltech_dir="./instagram_X"
caltech_dirr="./instagram_O/TEST"
categories=["coat","dress","pullover","shirt","t"]
nb_classes=len(categories)

In [4]:
image_w=64 
image_h=64

### TEST 데이터 불러오기

In [5]:
xx=[]
yy=[]
for idx, cat in enumerate(categories):
    # 레이블 지정 ---4
    label=[0 for i in range(nb_classes)]
    label[idx]=1
    # 이미지 ---5
    image_dirr=caltech_dirr+"/"+cat
    files=glob.glob(image_dirr+"/*.*")
    for i, f in enumerate(files):
        img=Image.open(f) # ---6
        img=img.convert("RGB")
        img=img.resize((image_w, image_h))
        data=np.asarray(img)
        xx.append(data)
        yy.append(label)
        if i%10==0:
            print(i, "\n", data)
xx=np.array(xx)
yy=np.array(yy)

0 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[201 197 194]
  [198 194 191]
  [210 206 203]
  ...
  [194 190 187]
  [195 191 188]
  [195 191 188]]

 [[204 203 199]
  [205 204 200]
  [206 205 201]
  ...
  [198 193 190]
  [198 193 189]
  [197 192 188]]

 ...

 [[158 140 120]
  [156 138 118]
  [136 121 102]
  ...
  [247 243 242]
  [251 249 250]
  [237 236 232]]

 [[167 149 125]
  [149 127 104]
  [176 154 131]
  ...
  [250 248 249]
  [255 254 252]
  [243 242 240]]

 [[ 96  78  58]
  [116  93  75]
  [115  92  74]
  ...
  [237 235 236]
  [253 252 250]
  [225 224 222]]]
10 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 

130 
 [[[133 132 137]
  [136 135 140]
  [140 139 144]
  ...
  [184 189 195]
  [183 192 201]
  [189 194 200]]

 [[144 143 148]
  [150 149 154]
  [146 145 150]
  ...
  [183 188 194]
  [186 190 201]
  [191 191 199]]

 [[144 143 148]
  [141 140 145]
  [134 133 138]
  ...
  [192 199 207]
  [186 189 196]
  [189 192 199]]

 ...

 [[134 132 135]
  [139 137 140]
  [139 137 140]
  ...
  [156 156 154]
  [159 158 156]
  [160 159 157]]

 [[137 132 136]
  [143 138 142]
  [143 138 142]
  ...
  [154 153 151]
  [158 157 155]
  [161 160 158]]

 [[146 141 145]
  [148 143 147]
  [149 144 148]
  ...
  [154 153 151]
  [156 155 153]
  [161 160 158]]]
140 
 [[[241 242 244]
  [241 242 244]
  [240 241 243]
  ...
  [236 237 239]
  [236 237 239]
  [232 238 238]]

 [[240 241 243]
  [240 241 243]
  [240 241 243]
  ...
  [236 237 239]
  [236 237 239]
  [232 238 238]]

 [[239 240 242]
  [239 240 242]
  [239 240 242]
  ...
  [235 239 240]
  [236 237 239]
  [236 237 239]]

 ...

 [[247 248 252]
  [247 248 252]
  [247 2

260 
 [[[ 85  60  30]
  [ 78  54  28]
  [199 183 134]
  ...
  [152  33  39]
  [158  31  42]
  [159  39  48]]

 [[ 84  57  28]
  [ 78  50  26]
  [200 183 139]
  ...
  [231  32  39]
  [227  33  41]
  [223  37  42]]

 [[ 94  69  38]
  [ 77  53  25]
  [202 185 141]
  ...
  [236 255 255]
  [243  29  27]
  [255 245 255]]

 ...

 [[188 157 110]
  [210 184 147]
  [ 70  39  18]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[184 151 110]
  [191 158 117]
  [ 83  49  24]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[192 163 121]
  [170 141  99]
  [ 73  42  21]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
270 
 [[[195 171 143]
  [197 173 145]
  [197 173 145]
  ...
  [ 83  59  49]
  [ 63  49  38]
  [ 95  73  60]]

 [[195 171 145]
  [196 172 146]
  [197 173 147]
  ...
  [ 85  55  45]
  [ 89  64  59]
  [ 44  35  20]]

 [[195 175 148]
  [195 175 148]
  [196 176 149]
  ...
  [ 88  66  53]
  [ 60  42  32]
  [ 49  35  22]]

 ...

 [[241 225 209]
  [239 223 207]
  [243 2

390 
 [[[ 43  37  25]
  [ 82  76  62]
  [ 99  91  88]
  ...
  [  2  11  44]
  [  2  11  44]
  [  2  11  44]]

 [[ 27  21   9]
  [ 87  81  67]
  [102  94  91]
  ...
  [  2  11  44]
  [  2  11  44]
  [  2  11  44]]

 [[ 43  33  21]
  [ 95  89  77]
  [102  97  91]
  ...
  [  2  11  44]
  [  2  11  44]
  [  2  11  44]]

 ...

 [[  4   4   2]
  [  4   4   2]
  [  7   5   8]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  9   9   9]
  [ 12  12  12]
  [ 12  12  12]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  6   6   6]
  [  7   7   7]
  [  7   7   7]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
400 
 [[[ 98 103  71]
  [116 121  89]
  [ 85  88  61]
  ...
  [240 186 122]
  [191 202 170]
  [181 179 154]]

 [[125 131  97]
  [155 159 134]
  [125 128 101]
  ...
  [232 207 127]
  [189 197 160]
  [187 182 152]]

 [[145 148 117]
  [164 167 138]
  [158 161 130]
  ...
  [201 201 191]
  [193 198 176]
  [195 183 167]]

 ...

 [[200 194 180]
  [200 194 180]
  [201 1

520 
 [[[239 242 247]
  [239 242 247]
  [238 241 246]
  ...
  [213 212 207]
  [211 210 205]
  [212 211 206]]

 [[239 242 247]
  [239 242 247]
  [237 240 245]
  ...
  [212 211 206]
  [212 211 206]
  [213 212 207]]

 [[239 244 248]
  [238 243 247]
  [236 241 245]
  ...
  [213 212 207]
  [213 210 205]
  [211 212 206]]

 ...

 [[214 188 161]
  [207 181 158]
  [205 173 148]
  ...
  [178 178 178]
  [205 206 210]
  [217 218 222]]

 [[183 162 143]
  [213 187 162]
  [208 187 166]
  ...
  [169 169 167]
  [201 202 207]
  [214 215 220]]

 [[194 170 144]
  [203 172 152]
  [203 175 151]
  ...
  [171 167 164]
  [216 217 222]
  [213 214 219]]]
530 
 [[[247 242 238]
  [248 243 239]
  [246 243 234]
  ...
  [246 241 235]
  [247 244 237]
  [247 244 237]]

 [[247 242 238]
  [248 243 239]
  [246 243 234]
  ...
  [245 240 234]
  [247 244 237]
  [247 244 237]]

 [[247 242 238]
  [245 240 236]
  [247 244 239]
  ...
  [246 243 238]
  [247 244 237]
  [247 244 237]]

 ...

 [[183 176 158]
  [187 180 162]
  [199 1

650 
 [[[163 185 199]
  [150 174 186]
  [150 173 189]
  ...
  [178 187 192]
  [161 172 174]
  [190 201 203]]

 [[179 178 184]
  [170 179 194]
  [ 81 108 117]
  ...
  [167 176 181]
  [158 169 171]
  [187 198 200]]

 [[133  64  83]
  [155 172 192]
  [ 59  82  98]
  ...
  [171 180 185]
  [163 173 175]
  [189 199 201]]

 ...

 [[148 174 187]
  [ 79 120  90]
  [139 166 173]
  ...
  [149 167 177]
  [143 160 170]
  [146 163 173]]

 [[ 90 124 110]
  [113 145 130]
  [154 181 190]
  ...
  [147 161 172]
  [147 162 169]
  [148 163 170]]

 [[ 89 127 102]
  [121 151 161]
  [122 151 167]
  ...
  [147 169 182]
  [119 141 154]
  [118 140 153]]]
660 
 [[[219 210 203]
  [226 221 215]
  [227 223 220]
  ...
  [229 212 186]
  [228 212 186]
  [230 214 191]]

 [[217 208 201]
  [223 218 212]
  [225 221 218]
  ...
  [229 212 186]
  [228 212 189]
  [230 213 195]]

 [[215 208 202]
  [219 216 211]
  [218 217 212]
  ...
  [226 209 183]
  [229 212 186]
  [231 213 191]]

 ...

 [[238 231 238]
  [242 235 242]
  [244 2

780 
 [[[34 34 32]
  [34 34 32]
  [34 34 32]
  ...
  [85 79 57]
  [50 50 42]
  [40 42 37]]

 [[34 34 32]
  [34 34 32]
  [34 34 32]
  ...
  [68 65 50]
  [46 49 42]
  [33 39 35]]

 [[34 34 32]
  [34 34 32]
  [34 34 32]
  ...
  [49 49 39]
  [44 49 45]
  [44 53 52]]

 ...

 [[77 79 66]
  [79 81 68]
  [71 72 58]
  ...
  [88 82 58]
  [89 83 59]
  [95 89 65]]

 [[66 66 54]
  [77 77 65]
  [80 79 59]
  ...
  [83 77 53]
  [82 76 52]
  [85 79 55]]

 [[62 59 40]
  [70 67 48]
  [56 54 39]
  ...
  [81 75 51]
  [76 70 46]
  [78 72 48]]]
790 
 [[[209 175 147]
  [209 175 147]
  [209 175 147]
  ...
  [226 191 163]
  [224 190 162]
  [227 193 165]]

 [[209 175 147]
  [209 175 147]
  [208 174 146]
  ...
  [226 191 163]
  [226 192 164]
  [228 194 166]]

 [[209 174 146]
  [209 174 146]
  [208 174 146]
  ...
  [226 191 163]
  [225 191 163]
  [229 195 167]]

 ...

 [[122  82  70]
  [131  87  76]
  [138  94  85]
  ...
  [147 138  59]
  [ 42  31   0]
  [ 35   0   0]]

 [[129  89  77]
  [140  96  85]
  [126  82  

920 
 [[[230 227 218]
  [237 227 218]
  [228 221 213]
  ...
  [209 207 194]
  [210 206 194]
  [209 205 193]]

 [[237 227 217]
  [186 149  97]
  [165 158 148]
  ...
  [208 206 193]
  [209 205 193]
  [209 205 193]]

 [[239 225 224]
  [184 144 109]
  [157 140 124]
  ...
  [206 204 191]
  [209 205 193]
  [208 204 192]]

 ...

 [[143  98  69]
  [145 102  67]
  [142 101  69]
  ...
  [201 202 196]
  [110 109 107]
  [141 146 142]]

 [[136  97  66]
  [114  74  48]
  [126  85  55]
  ...
  [ 87  89  86]
  [119 115 103]
  [118 124 120]]

 [[148 104  75]
  [159 115  90]
  [128  87  57]
  ...
  [161 161 151]
  [ 55  65  66]
  [144 149 143]]]
930 
 [[[193 193 191]
  [200 200 200]
  [201 201 199]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[197 197 197]
  [201 201 203]
  [208 207 205]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[200 200 198]
  [210 202 200]
  [210 206 203]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[221 221 255]
  [207 211 238]
  [210 2

50 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
60 
 [[[243 242 248]
  [245 244 249]
  [255 255 255]
  ...
  [214 214 216]
  [199 199 201]
  [222 223 225]]

 [[245 244 250]
  [236 235 240]
  [255 255 255]
  ...
  [217 217 219]
  [191 191 193]
  [227 228 230]]

 [[244 243 249]
  [227 226 232]
  [255 255 255]
  ...
  [220 220 220]
  [191 191 193]
  [220 221 223]]

 ...

 [[ 82  90 101]
  [ 80  86  98]
  [ 84  87

180 
 [[[238 239 244]
  [238 239 244]
  [234 235 240]
  ...
  [208 207 212]
  [210 209 214]
  [209 208 213]]

 [[238 239 244]
  [239 240 245]
  [237 238 243]
  ...
  [209 208 213]
  [209 208 213]
  [209 208 213]]

 [[238 239 243]
  [238 239 243]
  [239 238 243]
  ...
  [209 208 213]
  [209 208 213]
  [209 208 213]]

 ...

 [[174 159 152]
  [204 189 182]
  [194 181 173]
  ...
  [106 114  77]
  [ 70  69  48]
  [108  99  84]]

 [[199 186 178]
  [179 166 158]
  [188 175 167]
  ...
  [236 227 210]
  [ 93  84  67]
  [197 188 171]]

 [[254 255 255]
  [254 255 255]
  [254 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
190 
 [[[231 229 230]
  [231 229 230]
  [228 226 227]
  ...
  [239 239 241]
  [240 240 242]
  [239 239 241]]

 [[231 229 230]
  [231 229 230]
  [231 229 230]
  ...
  [240 240 242]
  [240 240 242]
  [240 240 242]]

 [[231 229 230]
  [231 229 230]
  [232 230 231]
  ...
  [240 240 242]
  [241 241 243]
  [241 241 243]]

 ...

 [[215 216 210]
  [214 215 209]
  [216 2

310 
 [[[131 132 134]
  [ 19  24  28]
  [ 22  25  30]
  ...
  [135 115 104]
  [134 116 104]
  [136 118 106]]

 [[108 109 111]
  [ 21  26  30]
  [ 22  25  30]
  ...
  [172 160 148]
  [164 150 139]
  [170 156 145]]

 [[ 87  70  60]
  [ 26  27  32]
  [ 18  23  27]
  ...
  [182 173 164]
  [176 167 158]
  [182 173 164]]

 ...

 [[ 16  15  13]
  [ 20  19  17]
  [ 29  30  25]
  ...
  [139 139 131]
  [144  96  86]
  [129  72  65]]

 [[ 18  17  15]
  [ 39  38  33]
  [ 30  35  29]
  ...
  [131 133 132]
  [143 144 146]
  [142 143 145]]

 [[ 35  34  32]
  [ 58  57  52]
  [ 77  73  61]
  ...
  [142 144 143]
  [136 137 139]
  [140 141 143]]]
320 
 [[[192 145 115]
  [190 146 117]
  [210 180 152]
  ...
  [ 44  45  29]
  [ 79  73  61]
  [106 105  84]]

 [[192 145 115]
  [187 143 114]
  [207 177 149]
  ...
  [ 72  66  40]
  [ 66  68  55]
  [ 66  71  49]]

 [[188 143 110]
  [189 144 115]
  [207 173 148]
  ...
  [ 64  57  38]
  [ 37  39  26]
  [ 49  56  38]]

 ...

 [[136 118  96]
  [125 106  89]
  [129 1

440 
 [[[187 181 181]
  [181 175 175]
  [177 169 166]
  ...
  [167 156 154]
  [105  92  99]
  [110 105 102]]

 [[185 179 179]
  [179 173 173]
  [185 176 177]
  ...
  [128 112 112]
  [154 154 144]
  [ 66  96  88]]

 [[178 174 173]
  [181 172 173]
  [180 175 172]
  ...
  [ 38  47  46]
  [ 50  59  56]
  [ 66  66  66]]

 ...

 [[185 184 179]
  [180 179 174]
  [182 181 176]
  ...
  [171 167 158]
  [211 203 182]
  [181 171 162]]

 [[176 177 172]
  [174 175 170]
  [173 174 166]
  ...
  [171 167 158]
  [173 164 155]
  [181 172 167]]

 [[144 145 140]
  [166 167 162]
  [152 153 148]
  ...
  [174 170 161]
  [182 173 164]
  [182 173 168]]]
450 
 [[[199 201 213]
  [198 200 212]
  [200 202 214]
  ...
  [215 221 235]
  [215 221 235]
  [215 221 235]]

 [[199 202 209]
  [199 202 209]
  [200 202 214]
  ...
  [215 222 232]
  [215 222 232]
  [215 222 232]]

 [[201 201 211]
  [198 202 211]
  [201 203 215]
  ...
  [216 220 232]
  [217 221 232]
  [217 221 232]]

 ...

 [[205 207 219]
  [204 206 218]
  [204 2

580 
 [[[177 171 157]
  [254 250 247]
  [ 99  84  79]
  ...
  [197 198 202]
  [194 197 202]
  [202 205 210]]

 [[173 166 156]
  [237 233 234]
  [ 93  78  73]
  ...
  [201 200 205]
  [205 202 209]
  [205 202 209]]

 [[174 167 151]
  [ 97  91  91]
  [ 84  77  69]
  ...
  [199 199 201]
  [202 202 204]
  [202 202 204]]

 ...

 [[176 158 134]
  [193 175 153]
  [164 147 127]
  ...
  [228 213 194]
  [148 142 130]
  [115 101  88]]

 [[195 177 155]
  [196 178 156]
  [123 108  89]
  ...
  [211 193 181]
  [111 101  91]
  [114  98  85]]

 [[197 179 157]
  [191 173 151]
  [148 133 114]
  ...
  [106 100  84]
  [103  93  83]
  [112  96  83]]]
590 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

710 
 [[[233 233 233]
  [234 234 234]
  [234 234 234]
  ...
  [100  98 101]
  [124 124 122]
  [123 123 121]]

 [[235 235 235]
  [235 235 235]
  [234 234 234]
  ...
  [123 121 122]
  [183 183 183]
  [191 191 191]]

 [[234 234 234]
  [234 234 234]
  [234 234 234]
  ...
  [ 16  14  15]
  [206 204 205]
  [180 178 179]]

 ...

 [[176 167 158]
  [154 145 136]
  [161 151 141]
  ...
  [146 133 114]
  [149 134 115]
  [148 133 114]]

 [[191 182 173]
  [186 177 170]
  [173 165 154]
  ...
  [150 135 116]
  [147 132 113]
  [148 133 114]]

 [[132 124 111]
  [189 181 170]
  [187 179 168]
  ...
  [147 132 113]
  [146 131 112]
  [147 132 113]]]
720 
 [[[213 172 170]
  [234 229 235]
  [145  58  31]
  ...
  [163 154 137]
  [160 151 136]
  [156 147 132]]

 [[ 61  24  18]
  [108  78  78]
  [139 111 123]
  ...
  [164 155 138]
  [176 173 158]
  [178 175 160]]

 [[148 128 117]
  [165 146 139]
  [ 41  22  16]
  ...
  [139 122 104]
  [145 139 127]
  [151 145 133]]

 ...

 [[223 214 205]
  [220 209 203]
  [229 2

840 
 [[[ 85  94  65]
  [ 54  64  27]
  [ 75  82  30]
  ...
  [204 189 168]
  [200 188 164]
  [200 188 164]]

 [[ 68  77  46]
  [ 11  19   0]
  [ 48  56   7]
  ...
  [208 193 172]
  [197 185 161]
  [199 187 163]]

 [[ 55  67  53]
  [ 26  36  11]
  [ 67  73  39]
  ...
  [205 193 171]
  [202 190 166]
  [201 189 165]]

 ...

 [[156 121  79]
  [153 118  76]
  [173 135  96]
  ...
  [215 198 172]
  [205 188 162]
  [204 187 161]]

 [[164 127  85]
  [131  97  59]
  [194 159 127]
  ...
  [213 193 168]
  [207 190 164]
  [207 190 164]]

 [[161 123  86]
  [196 162 127]
  [188 157 128]
  ...
  [195 175 150]
  [205 188 162]
  [204 187 161]]]
850 
 [[[237 234 227]
  [237 234 227]
  [237 234 227]
  ...
  [233 231 219]
  [233 231 219]
  [233 231 219]]

 [[237 234 227]
  [237 234 227]
  [237 234 227]
  ...
  [233 231 219]
  [233 231 219]
  [233 231 219]]

 [[236 233 226]
  [237 234 227]
  [237 234 227]
  ...
  [233 231 219]
  [233 231 219]
  [233 231 219]]

 ...

 [[ 71  78  24]
  [ 77  94  39]
  [ 61  

970 
 [[[220 220 222]
  [220 220 222]
  [220 220 222]
  ...
  [222 221 226]
  [223 222 227]
  [222 221 226]]

 [[219 219 221]
  [220 220 222]
  [220 220 222]
  ...
  [221 220 225]
  [222 221 226]
  [222 221 226]]

 [[219 219 221]
  [219 219 221]
  [219 219 221]
  ...
  [223 222 227]
  [223 222 227]
  [223 222 227]]

 ...

 [[195 193 196]
  [193 191 194]
  [192 190 193]
  ...
  [190 189 194]
  [191 190 195]
  [190 189 194]]

 [[194 192 195]
  [193 191 194]
  [191 189 192]
  ...
  [193 192 197]
  [190 189 194]
  [189 188 193]]

 [[194 192 195]
  [194 192 195]
  [192 190 193]
  ...
  [190 189 194]
  [190 189 194]
  [190 189 194]]]
980 
 [[[204 201 196]
  [201 198 193]
  [195 190 184]
  ...
  [247 248 252]
  [242 242 240]
  [242 242 240]]

 [[204 201 196]
  [202 199 194]
  [203 198 195]
  ...
  [245 246 250]
  [242 242 240]
  [242 242 240]]

 [[219 216 211]
  [206 203 198]
  [199 194 190]
  ...
  [246 250 249]
  [238 238 236]
  [242 242 240]]

 ...

 [[137 106  86]
  [126  95  75]
  [134 1

100 
 [[[233 227 215]
  [233 227 215]
  [232 224 213]
  ...
  [198 194 183]
  [199 195 186]
  [200 196 187]]

 [[231 225 213]
  [231 225 213]
  [231 223 212]
  ...
  [202 198 187]
  [202 198 189]
  [201 197 188]]

 [[230 224 212]
  [230 224 212]
  [229 223 211]
  ...
  [201 197 188]
  [202 198 189]
  [204 200 191]]

 ...

 [[ 12  34  47]
  [  5  27  40]
  [  8  30  43]
  ...
  [ 90  61  43]
  [119  83  57]
  [108  72  46]]

 [[  8  31  45]
  [  1  20  35]
  [  7  29  42]
  ...
  [ 95  68  49]
  [123  88  60]
  [ 91  56  28]]

 [[ 12  31  46]
  [ 14  30  46]
  [  4  22  36]
  ...
  [ 98  71  52]
  [101  66  34]
  [111  76  44]]]
110 
 [[[187 165 167]
  [199 177 179]
  [115  94  93]
  ...
  [201 189 175]
  [192 176 160]
  [191 175 159]]

 [[169 147 149]
  [168 146 148]
  [133 108 104]
  ...
  [186 174 160]
  [203 187 171]
  [190 174 158]]

 [[183 161 163]
  [155 133 135]
  [182 158 158]
  ...
  [225 212 196]
  [226 210 195]
  [224 209 190]]

 ...

 [[176 173 168]
  [185 182 177]
  [181 1

230 
 [[[151 147 136]
  [152 148 137]
  [157 153 142]
  ...
  [136 130 114]
  [138 133 114]
  [138 133 114]]

 [[155 151 140]
  [151 147 136]
  [157 153 142]
  ...
  [132 131 113]
  [130 125 106]
  [139 134 115]]

 [[158 154 143]
  [155 151 140]
  [155 151 140]
  ...
  [135 129 113]
  [136 131 112]
  [136 131 112]]

 ...

 [[197 198 193]
  [188 188 186]
  [195 196 190]
  ...
  [172 179 171]
  [175 182 174]
  [177 184 176]]

 [[197 198 192]
  [193 194 188]
  [192 193 187]
  ...
  [170 177 169]
  [177 184 176]
  [177 184 176]]

 [[191 192 186]
  [193 194 188]
  [193 194 188]
  ...
  [171 178 170]
  [177 184 176]
  [177 184 176]]]
240 
 [[[246 241 238]
  [240 235 229]
  [237 230 222]
  ...
  [228 177 124]
  [229 179 126]
  [230 180 127]]

 [[248 243 240]
  [242 237 231]
  [238 234 225]
  ...
  [227 176 123]
  [228 178 125]
  [231 181 128]]

 [[250 246 243]
  [245 241 238]
  [241 236 232]
  ...
  [228 177 124]
  [229 179 126]
  [232 183 125]]

 ...

 [[223 208 203]
  [165 129 105]
  [255 2

360 
 [[[160 150 148]
  [163 153 151]
  [163 153 151]
  ...
  [110 101  94]
  [106  97  90]
  [104  95  88]]

 [[165 155 153]
  [165 155 153]
  [165 155 153]
  ...
  [106  97  90]
  [105  96  89]
  [104  95  88]]

 [[167 159 156]
  [168 160 157]
  [166 158 156]
  ...
  [108  99  92]
  [106  97  90]
  [103  94  87]]

 ...

 [[200 203 212]
  [203 207 206]
  [207 207 207]
  ...
  [175 171 168]
  [170 166 163]
  [159 160 155]]

 [[217 220 225]
  [219 222 227]
  [232 231 237]
  ...
  [ 21  21  23]
  [ 15  15  15]
  [ 13  13  13]]

 [[ 49  48  54]
  [ 49  48  54]
  [ 50  49  55]
  ...
  [ 31  30  36]
  [ 32  32  32]
  [ 27  27  27]]]
370 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

490 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
500 
 [[[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 ...

 [[254 254 254]
  [254 254 254]
  [254 2

620 
 [[[ 41  45  56]
  [ 35  35  43]
  [ 45  54  63]
  ...
  [210 209 205]
  [209 208 204]
  [209 208 204]]

 [[ 41  45  57]
  [ 47  49  48]
  [ 64  63  71]
  ...
  [209 208 204]
  [209 208 204]
  [209 208 204]]

 [[211 211 209]
  [253 254 249]
  [235 234 230]
  ...
  [208 207 203]
  [207 206 202]
  [207 206 202]]

 ...

 [[184 178 166]
  [182 176 164]
  [183 174 165]
  ...
  [201 200 195]
  [204 199 193]
  [203 199 188]]

 [[190 180 171]
  [189 179 170]
  [189 180 171]
  ...
  [203 200 195]
  [204 199 193]
  [204 199 193]]

 [[192 182 173]
  [193 183 174]
  [189 180 171]
  ...
  [202 199 194]
  [201 196 190]
  [198 193 187]]]
630 
 [[[251 236 231]
  [216 148 149]
  [223 132 139]
  ...
  [204 205 189]
  [203 204 190]
  [203 204 190]]

 [[217 114 117]
  [214 134 133]
  [236 149 155]
  ...
  [196 197 181]
  [200 197 180]
  [200 197 180]]

 [[214  87  98]
  [218 107 114]
  [224 133 138]
  ...
  [191 192 176]
  [193 191 176]
  [194 192 177]]

 ...

 [[211 184 155]
  [213 188 158]
  [213 1

760 
 [[[164 153 149]
  [219 209 197]
  [237 226 224]
  ...
  [178 169 172]
  [144 135 136]
  [167 158 159]]

 [[182 171 167]
  [165 153 153]
  [184 173 171]
  ...
  [192 189 184]
  [161 152 157]
  [176 167 172]]

 [[149 138 134]
  [156 144 144]
  [159 147 147]
  ...
  [184 172 172]
  [196 184 184]
  [169 165 162]]

 ...

 [[120 113 105]
  [ 92  84  81]
  [118 110 107]
  ...
  [197 116  37]
  [238 130  68]
  [ 63  35  13]]

 [[ 85  76  71]
  [126 117 112]
  [121 112 107]
  ...
  [232 200 113]
  [201 128  77]
  [132  95  69]]

 [[ 92  87  84]
  [135 130 127]
  [113 103 102]
  ...
  [224 155  80]
  [233 108  78]
  [173 135 132]]]
770 
 [[[210 214 226]
  [210 214 226]
  [210 216 228]
  ...
  [ 81 147 197]
  [ 78 145 197]
  [ 76 143 195]]

 [[209 213 225]
  [210 214 226]
  [209 215 227]
  ...
  [ 83 148 202]
  [ 82 145 198]
  [ 80 143 196]]

 [[205 213 224]
  [205 213 224]
  [212 218 230]
  ...
  [ 92 154 203]
  [ 79 142 193]
  [ 83 146 197]]

 ...

 [[205 186 169]
  [117  89  75]
  [ 93  

890 
 [[[170 190 215]
  [172 192 217]
  [174 194 219]
  ...
  [175 196 223]
  [169 193 219]
  [170 194 220]]

 [[171 191 216]
  [172 192 217]
  [173 195 219]
  ...
  [173 194 221]
  [168 192 218]
  [167 191 217]]

 [[170 192 216]
  [167 189 213]
  [166 188 212]
  ...
  [173 195 219]
  [170 192 216]
  [169 191 215]]

 ...

 [[ 97  88  71]
  [162 149 132]
  [100  89  69]
  ...
  [114 106  87]
  [105  94  76]
  [132 121 103]]

 [[127 115  91]
  [ 88  75  56]
  [ 42  31  13]
  ...
  [124 117  98]
  [116 107  90]
  [118 106  84]]

 [[ 98  90  69]
  [ 72  63  46]
  [ 60  54  30]
  ...
  [146 135 117]
  [140 133 104]
  [130 118  94]]]
900 
 [[[105 103  91]
  [ 31  28  23]
  [ 40  39  35]
  ...
  [ 71  67  64]
  [ 66  63  58]
  [ 72  69  64]]

 [[104  99  80]
  [101  94  84]
  [ 15  13  14]
  ...
  [ 67  63  60]
  [ 85  82  77]
  [ 57  54  49]]

 [[110 104  88]
  [107 102  82]
  [ 23  20  13]
  ...
  [ 69  66  61]
  [ 70  67  60]
  [ 71  67  64]]

 ...

 [[203 201 202]
  [199 201 200]
  [200 2

20 
 [[[ 33  31  42]
  [163 199 251]
  [164 201 254]
  ...
  [ 26  25  20]
  [  3  11  22]
  [125 135 137]]

 [[  0   8  31]
  [180 209 253]
  [173 211 255]
  ...
  [ 22  21  16]
  [ 26  25  30]
  [  4   3   8]]

 [[169 174 196]
  [148 168  45]
  [173 194 255]
  ...
  [ 30  27  22]
  [ 12  10  13]
  [ 35  41  13]]

 ...

 [[ 22  18  19]
  [205 188 172]
  [112  99  90]
  ...
  [ 96  69  48]
  [141 112  98]
  [150 118  97]]

 [[ 17  17  15]
  [ 34  16  16]
  [ 32  22  20]
  ...
  [143 114  96]
  [158 118  92]
  [162 128 100]]

 [[ 15  15  15]
  [ 25   9   0]
  [ 12   0   0]
  ...
  [146 124 111]
  [162 139 123]
  [129 101  87]]]
30 
 [[[105 103  29]
  [ 47  57   7]
  [ 77  63  16]
  ...
  [ 44  54  17]
  [ 83  97  64]
  [ 39  42   0]]

 [[157 151  67]
  [ 98 102  43]
  [144 106  97]
  ...
  [ 20  29   2]
  [ 26  36   2]
  [ 36  44   7]]

 [[135 125 116]
  [154 143 141]
  [153 145 132]
  ...
  [ 69  70  65]
  [ 49  53  38]
  [  5   8   0]]

 ...

 [[153 114  55]
  [217 170 126]
  [187 147

150 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
160 
 [[[144 138 148]
  [155 150 156]
  [113 111 112]
  ...
  [226 216 207]
  [227 218 209]
  [230 217 209]]

 [[255 254 252]
  [183 180 187]
  [248 255 255]
  ...
  [232 217 210]
  [233 220 212]
  [236 219 212]]

 [[252 250 251]
  [166 173 181]
  [246 255 255]
  ...
  [234 219 212]
  [234 219 212]
  [237 222 215]]

 ...

 [[209 193 167]
  [206 190 164]
  [204 1

280 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
290 
 [[[ 35  35  35]
  [ 39  35  36]
  [175 172 157]
  ...
  [227 215 201]
  [224 212 198]
  [214 202 188]]

 [[ 37  37  37]
  [ 39  35  36]
  [177 174 159]
  ...
  [198 186 172]
  [232 221 203]
  [213 202 184]]

 [[ 45  43  44]
  [ 39  37  38]
  [ 27  33  33]
  ...
  [228 215 199]
  [231 218 202]
  [229 216 200]]

 ...

 [[ 86  86  86]
  [152 152 150]
  [ 73  

420 
 [[[168 194 217]
  [170 196 219]
  [171 198 219]
  ...
  [209 213 224]
  [206 210 221]
  [201 205 216]]

 [[174 196 219]
  [175 197 220]
  [175 197 218]
  ...
  [209 213 224]
  [207 211 222]
  [206 210 221]]

 [[175 197 218]
  [175 197 218]
  [175 197 218]
  ...
  [216 217 222]
  [211 219 222]
  [215 218 223]]

 ...

 [[127 114  97]
  [104  93  63]
  [ 79  68  38]
  ...
  [133 144 146]
  [133 143 145]
  [133 143 145]]

 [[132 132 130]
  [ 66  70  71]
  [171 171 161]
  ...
  [125 135 137]
  [121 131 133]
  [129 139 141]]

 [[119 123 132]
  [110 109 114]
  [162 161 157]
  ...
  [119 129 131]
  [118 128 130]
  [117 127 129]]]
430 
 [[[202 192 190]
  [200 190 188]
  [201 192 187]
  ...
  [234 232 233]
  [244 242 243]
  [240 242 241]]

 [[203 193 191]
  [204 194 192]
  [199 190 185]
  ...
  [211 203 200]
  [210 202 199]
  [209 201 198]]

 [[203 193 191]
  [204 194 192]
  [204 194 192]
  ...
  [210 200 198]
  [210 200 198]
  [209 199 197]]

 ...

 [[207 196 192]
  [206 195 191]
  [203 1

550 
 [[[115 119 120]
  [115 119 120]
  [116 120 123]
  ...
  [ 65  85  84]
  [ 99 128 108]
  [159 171 169]]

 [[115 119 120]
  [115 119 120]
  [117 121 124]
  ...
  [ 59 100  70]
  [123 141 125]
  [162 174 172]]

 [[116 120 121]
  [117 121 122]
  [117 121 124]
  ...
  [128  98  98]
  [ 62  85  69]
  [155 169 169]]

 ...

 [[ 15  16  18]
  [ 15  16  18]
  [ 11  12  14]
  ...
  [  8   9  11]
  [ 11  12  14]
  [  8   9  11]]

 [[ 10  11  13]
  [ 11  12  14]
  [ 12  13  15]
  ...
  [ 13  13  15]
  [ 12  13  15]
  [  7   8  10]]

 [[ 12  13  15]
  [ 14  15  17]
  [ 13  14  16]
  ...
  [  7   7   9]
  [  8   9  11]
  [  4   5   7]]]
560 
 [[[ 36  37  39]
  [ 33  34  36]
  [ 29  30  32]
  ...
  [ 26  19  11]
  [ 74  53  32]
  [ 63  47  31]]

 [[ 37  38  40]
  [ 30  31  33]
  [ 24  25  27]
  ...
  [ 44  36  25]
  [ 53  35  15]
  [ 55  33  12]]

 [[ 36  34  37]
  [ 31  32  34]
  [ 28  29  31]
  ...
  [ 36  27  12]
  [ 39  26  10]
  [ 61  40  21]]

 ...

 [[121 117 108]
  [122 118 107]
  [155 1

 [[[136 102  93]
  [ 96  89  81]
  [149 101  99]
  ...
  [156  99  79]
  [151 100  81]
  [148  98  73]]

 [[138 130 127]
  [141  99  85]
  [133 120 104]
  ...
  [154  93  74]
  [132  90  66]
  [ 95  89  77]]

 [[133 101  90]
  [139 111 107]
  [152 122 112]
  ...
  [171 143 131]
  [164 102  91]
  [162 106  81]]

 ...

 [[230 228 239]
  [212 210 221]
  [219 218 232]
  ...
  [ 88  87  82]
  [ 91  90  88]
  [ 94  88  88]]

 [[213 203 214]
  [206 203 212]
  [208 210 222]
  ...
  [ 88  89  84]
  [ 87  88  82]
  [ 81  82  76]]

 [[209 203 213]
  [211 211 219]
  [200 187 194]
  ...
  [118 116 104]
  [ 88  89  83]
  [ 77  78  72]]]
690 
 [[[176 169 153]
  [174 166 153]
  [170 164 150]
  ...
  [206 197 182]
  [212 203 188]
  [211 201 189]]

 [[174 168 154]
  [171 163 152]
  [174 164 152]
  ...
  [207 198 183]
  [214 205 190]
  [212 202 190]]

 [[176 168 155]
  [174 164 152]
  [170 162 149]
  ...
  [208 196 182]
  [210 201 186]
  [213 203 191]]

 ...

 [[164 156 143]
  [168 160 147]
  [159 151 13

810 
 [[[ 78 132 206]
  [ 78 132 206]
  [ 78 132 206]
  ...
  [ 75 124 193]
  [ 73 123 192]
  [ 72 122 191]]

 [[ 81 135 209]
  [ 78 132 206]
  [ 79 133 207]
  ...
  [ 78 127 196]
  [ 73 123 192]
  [ 76 126 195]]

 [[ 83 137 211]
  [ 82 136 210]
  [ 84 138 212]
  ...
  [ 73 126 192]
  [ 76 126 195]
  [ 77 127 196]]

 ...

 [[ 52  56  67]
  [ 50  54  65]
  [ 48  55  65]
  ...
  [ 48  52  63]
  [ 51  51  63]
  [ 44  48  59]]

 [[ 54  58  67]
  [ 50  54  63]
  [ 56  58  71]
  ...
  [ 41  45  57]
  [ 35  39  50]
  [ 45  49  60]]

 [[ 63  67  79]
  [ 61  65  77]
  [ 61  67  79]
  ...
  [ 53  57  69]
  [ 62  66  77]
  [ 53  57  68]]]
820 
 [[[235 225 213]
  [235 225 213]
  [238 226 214]
  ...
  [222 218 215]
  [222 218 215]
  [222 218 215]]

 [[235 223 211]
  [235 223 211]
  [235 223 211]
  ...
  [222 218 215]
  [222 218 215]
  [223 219 216]]

 [[233 221 209]
  [234 222 210]
  [234 222 210]
  ...
  [222 218 215]
  [223 219 216]
  [223 219 216]]

 ...

 [[178 163 156]
  [179 164 157]
  [181 1

940 
 [[[143 117  90]
  [131 105  82]
  [127  98  66]
  ...
  [106  75  47]
  [124  90  62]
  [124  90  62]]

 [[141 115  88]
  [147 121  98]
  [130 101  69]
  ...
  [100  69  41]
  [117  84  51]
  [118  85  52]]

 [[125  98  69]
  [110  82  58]
  [116  85  54]
  ...
  [123  92  64]
  [121  88  57]
  [119  86  55]]

 ...

 [[176 167 158]
  [179 170 161]
  [177 170 160]
  ...
  [186 177 168]
  [178 170 159]
  [177 170 154]]

 [[177 168 159]
  [180 171 162]
  [174 165 156]
  ...
  [178 168 158]
  [176 168 155]
  [171 163 150]]

 [[180 171 162]
  [179 170 161]
  [176 167 158]
  ...
  [176 166 156]
  [175 166 157]
  [173 164 155]]]
950 
 [[[131 178 224]
  [132 179 225]
  [134 178 225]
  ...
  [250 251 255]
  [248 248 255]
  [246 246 254]]

 [[139 182 225]
  [137 180 223]
  [136 181 223]
  ...
  [247 248 253]
  [248 248 255]
  [248 248 255]]

 [[140 183 226]
  [139 182 225]
  [138 181 224]
  ...
  [239 242 249]
  [250 251 255]
  [251 252 255]]

 ...

 [[217 213 212]
  [226 222 221]
  [206 2

70 
 [[[168 167 162]
  [169 168 163]
  [167 166 162]
  ...
  [205 202 195]
  [172 169 162]
  [ 86  83  76]]

 [[169 168 163]
  [138 137 132]
  [164 163 159]
  ...
  [222 219 212]
  [214 211 204]
  [207 204 197]]

 [[164 163 159]
  [161 160 156]
  [186 185 181]
  ...
  [120 117 110]
  [191 188 181]
  [176 173 166]]

 ...

 [[225 214 194]
  [255 250 228]
  [250 242 223]
  ...
  [178 172 160]
  [221 215 203]
  [185 179 167]]

 [[136 131 112]
  [117 111  97]
  [255 252 235]
  ...
  [213 207 195]
  [195 189 177]
  [244 238 226]]

 [[241 236 217]
  [231 225 211]
  [177 167 158]
  ...
  [165 159 147]
  [210 204 192]
  [208 202 190]]]
80 
 [[[238 234 231]
  [239 235 232]
  [239 236 231]
  ...
  [232 231 227]
  [233 232 228]
  [233 232 228]]

 [[239 235 232]
  [239 235 232]
  [240 237 232]
  ...
  [233 232 228]
  [229 228 224]
  [232 231 227]]

 [[239 236 231]
  [240 237 232]
  [240 237 232]
  ...
  [234 233 229]
  [234 233 229]
  [233 232 228]]

 ...

 [[133 111  88]
  [145 119  92]
  [137 113

200 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
210 
 [[[ 53  51  64]
  [ 52  50  63]
  [ 41  39  50]
  ...
  [179 160 145]
  [188 166 142]
  [190 168 144]]

 [[ 43  41  54]
  [ 52  50  63]
  [ 48  46  57]
  ...
  [143 122  95]
  [175 151 123]
  [181 157 129]]

 [[ 39  37  50]
  [ 52  50  61]
  [ 50  48  59]
  ...
  [119  90  58]
  [ 98 107  76]
  [166 162 137]]

 ...

 [[152 150 129]
  [168 163 134]
  [162 1

330 
 [[[189 195 195]
  [189 195 195]
  [188 194 194]
  ...
  [205 210 204]
  [207 209 206]
  [208 210 207]]

 [[188 194 194]
  [188 194 194]
  [187 193 193]
  ...
  [206 211 205]
  [207 213 209]
  [206 212 208]]

 [[187 193 193]
  [188 194 194]
  [187 193 193]
  ...
  [201 206 200]
  [204 211 204]
  [204 211 204]]

 ...

 [[148 132 116]
  [175 157 137]
  [140 121 104]
  ...
  [148 136 124]
  [165 151 140]
  [123 109  98]]

 [[221 204 188]
  [152 135 119]
  [129 111  91]
  ...
  [150 138 124]
  [163 149 136]
  [128 114 101]]

 [[217 200 184]
  [144 127 111]
  [116  97  82]
  ...
  [171 159 145]
  [144 130 117]
  [172 158 145]]]
340 
 [[[241 245 248]
  [242 246 249]
  [244 243 249]
  ...
  [ 53  47  33]
  [ 53  47  35]
  [ 52  46  34]]

 [[227 230 237]
  [247 250 255]
  [243 242 248]
  ...
  [ 59  54  35]
  [ 54  48  32]
  [ 54  48  32]]

 [[235 238 245]
  [235 238 245]
  [235 240 244]
  ...
  [ 72  61  39]
  [ 54  47  28]
  [ 63  56  37]]

 ...

 [[120 117 124]
  [145 146 151]
  [ 79  

460 
 [[[188 181 163]
  [185 178 160]
  [182 175 157]
  ...
  [207 201 187]
  [208 202 190]
  [210 204 192]]

 [[188 181 163]
  [185 178 160]
  [183 176 158]
  ...
  [204 198 184]
  [207 201 185]
  [208 202 186]]

 [[191 184 166]
  [185 178 160]
  [184 177 159]
  ...
  [199 193 177]
  [205 199 183]
  [206 200 184]]

 ...

 [[208 201 185]
  [209 202 183]
  [207 199 178]
  ...
  [231 232 234]
  [230 231 233]
  [228 229 231]]

 [[209 201 190]
  [209 202 186]
  [207 199 180]
  ...
  [231 232 234]
  [230 231 233]
  [229 230 232]]

 [[209 201 190]
  [209 202 186]
  [207 199 180]
  ...
  [232 233 235]
  [231 232 234]
  [230 231 233]]]
470 
 [[[241 229 233]
  [234 222 226]
  [235 224 230]
  ...
  [207  78  73]
  [234 122 110]
  [185 137 117]]

 [[238 226 230]
  [235 223 227]
  [238 227 233]
  ...
  [161  73  69]
  [199  93  79]
  [138 132 110]]

 [[229 227 228]
  [234 236 235]
  [235 239 240]
  ...
  [144 117  96]
  [230 116 106]
  [129 127 102]]

 ...

 [[209 151 165]
  [143  33  72]
  [145  

590 
 [[[158 156 157]
  [158 156 157]
  [158 158 158]
  ...
  [185 186 190]
  [186 187 191]
  [187 188 192]]

 [[158 156 157]
  [158 156 157]
  [158 158 158]
  ...
  [185 186 190]
  [187 188 192]
  [186 187 191]]

 [[156 156 156]
  [156 156 156]
  [158 158 158]
  ...
  [189 190 194]
  [185 189 192]
  [185 189 192]]

 ...

 [[153 149 146]
  [153 149 146]
  [152 149 144]
  ...
  [243 241 246]
  [180 172 170]
  [174 166 164]]

 [[153 149 146]
  [152 148 145]
  [153 150 145]
  ...
  [235 236 238]
  [173 168 165]
  [169 164 161]]

 [[152 148 145]
  [151 147 144]
  [150 147 142]
  ...
  [255 253 255]
  [169 164 161]
  [168 163 160]]]
600 
 [[[253 248 244]
  [210 205 201]
  [190 185 181]
  ...
  [134 128 114]
  [133 127 113]
  [133 127 113]]

 [[198 193 189]
  [213 208 204]
  [222 217 213]
  ...
  [134 128 114]
  [135 129 115]
  [134 128 114]]

 [[194 189 185]
  [210 205 201]
  [194 189 185]
  ...
  [135 129 115]
  [134 128 114]
  [133 127 113]]

 ...

 [[232 228 227]
  [231 227 226]
  [234 2

720 
 [[[255 254 242]
  [255 254 242]
  [230 219 199]
  ...
  [225 219 205]
  [228 222 206]
  [229 223 207]]

 [[255 254 242]
  [255 255 243]
  [231 220 200]
  ...
  [223 218 199]
  [226 220 204]
  [228 222 206]]

 [[254 254 242]
  [255 255 243]
  [228 223 203]
  ...
  [221 216 197]
  [224 219 200]
  [227 222 203]]

 ...

 [[254 254 254]
  [255 255 255]
  [224 214 202]
  ...
  [238 239 241]
  [237 238 240]
  [237 238 240]]

 [[254 254 254]
  [255 255 255]
  [227 217 205]
  ...
  [237 238 240]
  [237 238 240]
  [237 238 240]]

 [[253 253 253]
  [255 255 255]
  [227 217 205]
  ...
  [238 239 241]
  [237 238 240]
  [237 238 240]]]
730 
 [[[206 205 185]
  [214 214 190]
  [214 213 192]
  ...
  [233 229 226]
  [248 247 245]
  [254 253 251]]

 [[205 204 184]
  [211 211 187]
  [217 216 195]
  ...
  [212 208 205]
  [249 248 246]
  [241 240 238]]

 [[205 207 186]
  [210 207 188]
  [213 212 191]
  ...
  [227 223 220]
  [254 253 251]
  [221 220 218]]

 ...

 [[163 157 125]
  [167 161 129]
  [170 1

870 
 [[[228 218 209]
  [233 226 216]
  [157 148 139]
  ...
  [255 254 250]
  [251 245 245]
  [196 190 190]]

 [[110 100  91]
  [163 156 146]
  [255 253 242]
  ...
  [166 160 160]
  [ 91  85  85]
  [249 243 243]]

 [[215 206 197]
  [232 223 214]
  [130 123 113]
  ...
  [242 237 234]
  [241 236 233]
  [128 123 120]]

 ...

 [[197 188 179]
  [218 209 200]
  [252 242 233]
  ...
  [208 200 197]
  [211 210 206]
  [254 249 246]]

 [[161 154 144]
  [226 216 207]
  [199 190 181]
  ...
  [253 245 242]
  [229 224 221]
  [225 220 217]]

 [[254 247 237]
  [219 209 200]
  [247 238 229]
  ...
  [244 236 233]
  [146 141 138]
  [221 216 213]]]
880 
 [[[206 206 218]
  [204 204 216]
  [204 204 216]
  ...
  [191 191 201]
  [192 192 202]
  [189 189 199]]

 [[207 207 219]
  [209 209 221]
  [205 205 217]
  ...
  [197 197 207]
  [190 190 200]
  [190 190 200]]

 [[204 204 216]
  [206 206 218]
  [206 206 218]
  ...
  [194 194 204]
  [191 191 201]
  [192 192 202]]

 ...

 [[206 206 218]
  [205 205 217]
  [204 2

### TRAIN 데이터 불러오기

In [ ]:
import random
li=[21622, 14217, 21846, 17447, 18615]

In [ ]:
x=[]
y=[]
for i, m in enumerate(li):
    # 레이블 지정 ---4
    label=[0 for i in range(nb_classes)]
    label[i]=1
    num=[]
    for n in range(1,m+1):
        num.append(n)
    print(len(num))
    s=random.sample(num, 7000)
    print(len(s))
    image_dir=caltech_dir+"/"+categories[i]
    for b in s:
        b=str(b)
        files=glob.glob(image_dir + "/IMG (" + b + ").jpg")
        for i, f in enumerate(files):
            img=Image.open(f) # ---6
            img=img.convert("RGB")
            img=img.resize((image_w, image_h))
            data=np.asarray(img)
            x.append(data)
            y.append(label)
x=np.array(x)
y=np.array(y)

21622
7000


### 데이터 셋 분리 및 정규화

In [ ]:
# 학습 전용 데이터와 테스트 전용 데이터 구분 ---101
x_train=x
x_test=xx
y_train=y
y_test=yy
xy=(x_train, x_test, y_train, y_test)
np.save("./instagram_O/5obj.npy", xy)

print("ok,", len(y))

In [ ]:
categories=["coat","dress","pullover","shirt","t"]
nb_classes=len(categories)
image_w=64
image_h=64

In [ ]:
x_train, x_test, y_train, y_test = np.load("./instagram_O/5obj.npy", allow_pickle=True)
#데이터 정규화하기
x_train = x_train.astype("float")/255
x_test = x_test.astype("float")/255
print('x_train:', x_train.shape)
len(y_train)

### 모델 학습(1)

In [12]:
import keras.backend.tensorflow_backend as K
with K.tf.device('/device:GPU:2'):
    model = Sequential()
    model.add(Convolution2D(32,3,3,border_mode='same',input_shape=x_train.shape[1:]))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    #모델 훈련하기
    model.fit(x_train, y_train, batch_size=50, nb_epoch=10)

/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(64, 64, 3..., padding="same")`
  after removing the cwd from sys.path.
/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:8: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
  
/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:10: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
  # Remove the CWD from sys.path while we load stuff.
/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:23: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/10
35000/35000 [==============================] - 14s 391us/step - loss: 1.5937 - acc: 0.2482
Epoch 2/10
35000/35000 [==============================] - 9s 257us/step - loss: 1.5481 - acc: 0.2986
Epoch 3/10
35000/35000 [==============================] - 9s 257us/step - loss: 1.4985 - acc: 0.3419
Epoch 4/10
35000/35000 [==============================] - 9s 262us/step - loss: 1.4214 - acc: 0.3914
Epoch 5/10
35000/35000 [==============================] - 10s 287us/step - loss: 1.3107 - acc: 0.4533
Epoch 6/10
35000/35000 [==============================] - 10s 291us/step - loss: 1.1718 - acc: 0.5237
Epoch 7/10
35000/35000 [==============================] - 10s 285us/step - loss: 1.0321 - acc: 0.5934
Epoch 8/10
35000/35000 [==============================] - 10s 286us/step - loss: 0.8978 - acc: 0.6551
Epoch 9/10
35000/35000 [==============================] - 10s 277us/step - loss: 0.7960 - acc: 0.6968
Epoch 10/10
35000/35000 [==============================] - 10s 279us/step - loss: 0.7

### total accuracy

In [13]:
score = model.evaluate(x_test,y_test, verbose=0)
print('loss=', score[0])
print('accuracy=',score[1])

loss= 1.1841883945465088
accuracy= 0.5932


### 개별 accuracy

In [14]:
categories=["coat","dress","pullover","shirt","t"]
for i in range(5):
    yyy_test=[]
    xxx_test=[]
    for j in range(5000):
        if y_test[j][i]==1:
            yyy_test.append(y_test[j])
            xxx_test.append(x_test[j])
    yyy_test=np.array(yyy_test)
    xxx_test=np.array(xxx_test)
    score = model.evaluate(xxx_test,yyy_test, verbose=0)
    print(categories[i]+'의 loss=', score[0])
    print(categories[i]+'의 accuracy=',score[1])
    print('-----------------------------------')

coat의 loss= 1.4034975261688232
coat의 accuracy= 0.523
-----------------------------------
dress의 loss= 1.2413065967559815
dress의 accuracy= 0.624
-----------------------------------
pullover의 loss= 1.149779990196228
pullover의 accuracy= 0.62
-----------------------------------
shirt의 loss= 1.1151421937942505
shirt의 accuracy= 0.554
-----------------------------------
t의 loss= 1.0112156734466553
t의 accuracy= 0.645
-----------------------------------


### 모델 학습(2)

In [15]:
import keras.backend.tensorflow_backend as K
with K.tf.device('/device:GPU:2'):
    model = Sequential()
    model.add(Convolution2D(32,3,3,border_mode='same',input_shape=x_train.shape[1:]))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    #모델 훈련하기
    model.fit(x_train, y_train, batch_size=50, nb_epoch=100)

/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(64, 64, 3..., padding="same")`
  after removing the cwd from sys.path.
/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:8: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
  
/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:10: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
  # Remove the CWD from sys.path while we load stuff.
/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:23: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/100
35000/35000 [==============================] - 11s 305us/step - loss: 1.6116 - acc: 0.2092
Epoch 2/100
35000/35000 [==============================] - 9s 258us/step - loss: 1.5708 - acc: 0.2786
Epoch 3/100
35000/35000 [==============================] - 9s 264us/step - loss: 1.5343 - acc: 0.3090
Epoch 4/100
35000/35000 [==============================] - 9s 266us/step - loss: 1.4839 - acc: 0.3492
Epoch 5/100
35000/35000 [==============================] - 9s 256us/step - loss: 1.4120 - acc: 0.3949
Epoch 6/100
35000/35000 [==============================] - 10s 274us/step - loss: 1.3177 - acc: 0.4521
Epoch 7/100
35000/35000 [==============================] - 9s 248us/step - loss: 1.1942 - acc: 0.5113
Epoch 8/100
35000/35000 [==============================] - 9s 266us/step - loss: 1.0675 - acc: 0.5738
Epoch 9/100
35000/35000 [==============================] - 9s 266us/step - loss: 0.9478 - acc: 0.6316
Epoch 10/100
35000/35000 [==============================] - 9s 247us/step - loss

### total accuracy

In [16]:
score = model.evaluate(x_test,y_test, verbose=0)
print('loss=', score[0])
print('accuracy=',score[1])

loss= 1.6665534477233888
accuracy= 0.6274


### 개별 accuracy

In [17]:
categories=["coat","dress","pullover","shirt","t"]
for i in range(5):
    yyy_test=[]
    xxx_test=[]
    for j in range(5000):
        if y_test[j][i]==1:
            yyy_test.append(y_test[j])
            xxx_test.append(x_test[j])
    yyy_test=np.array(yyy_test)
    xxx_test=np.array(xxx_test)
    score = model.evaluate(xxx_test,yyy_test, verbose=0)
    print(categories[i]+'의 loss=', score[0])
    print(categories[i]+'의 accuracy=',score[1])
    print('-----------------------------------')

coat의 loss= 1.9877653198242187
coat의 accuracy= 0.577
-----------------------------------
dress의 loss= 1.644675274848938
dress의 accuracy= 0.629
-----------------------------------
pullover의 loss= 1.5907703341841697
pullover의 accuracy= 0.667
-----------------------------------
shirt의 loss= 1.4810572285652162
shirt의 accuracy= 0.633
-----------------------------------
t의 loss= 1.6284991207122803
t의 accuracy= 0.631
-----------------------------------


### 모델 학습(3)

In [18]:
import keras.backend.tensorflow_backend as K
with K.tf.device('/device:GPU:3'):
    model = Sequential()
    model.add(Convolution2D(32,3,3,border_mode='same',input_shape=x_train.shape[1:]))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    #모델 훈련하기
    model.fit(x_train, y_train, batch_size=50, nb_epoch=1000)

/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(64, 64, 3..., padding="same")`
  after removing the cwd from sys.path.
/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:8: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
  
/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:10: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
  # Remove the CWD from sys.path while we load stuff.
/home/datacenter/.local/lib/python3.6/site-packages/ipykernel_launcher.py:23: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/1000
35000/35000 [==============================] - 11s 319us/step - loss: 1.6163 - acc: 0.1974
Epoch 2/1000
35000/35000 [==============================] - 10s 274us/step - loss: 1.6102 - acc: 0.2007
Epoch 3/1000
35000/35000 [==============================] - 9s 270us/step - loss: 1.5905 - acc: 0.2523
Epoch 4/1000
35000/35000 [==============================] - 10s 282us/step - loss: 1.5531 - acc: 0.2972
Epoch 5/1000
35000/35000 [==============================] - 9s 257us/step - loss: 1.5070 - acc: 0.3311
Epoch 6/1000
35000/35000 [==============================] - 9s 271us/step - loss: 1.4444 - acc: 0.3762
Epoch 7/1000
35000/35000 [==============================] - 9s 271us/step - loss: 1.3663 - acc: 0.4238
Epoch 8/1000
35000/35000 [==============================] - 10s 279us/step - loss: 1.2676 - acc: 0.4779
Epoch 9/1000
35000/35000 [==============================] - 9s 264us/step - loss: 1.1524 - acc: 0.5331
Epoch 10/1000
35000/35000 [==============================] - 10s 284u

35000/35000 [==============================] - 10s 283us/step - loss: 0.1189 - acc: 0.9629
Epoch 157/1000
35000/35000 [==============================] - 10s 279us/step - loss: 0.1279 - acc: 0.9601
Epoch 158/1000
35000/35000 [==============================] - 10s 276us/step - loss: 0.1213 - acc: 0.9615
Epoch 159/1000
35000/35000 [==============================] - 10s 275us/step - loss: 0.1217 - acc: 0.9611
Epoch 160/1000
35000/35000 [==============================] - 10s 281us/step - loss: 0.1236 - acc: 0.9605
Epoch 161/1000
35000/35000 [==============================] - 10s 284us/step - loss: 0.1139 - acc: 0.9638
Epoch 162/1000
35000/35000 [==============================] - 10s 281us/step - loss: 0.1263 - acc: 0.9587
Epoch 163/1000
35000/35000 [==============================] - 10s 279us/step - loss: 0.1173 - acc: 0.9624
Epoch 164/1000
35000/35000 [==============================] - 10s 284us/step - loss: 0.1205 - acc: 0.9619
Epoch 165/1000
35000/35000 [==============================] -

35000/35000 [==============================] - 10s 281us/step - loss: 0.1122 - acc: 0.9666
Epoch 311/1000
35000/35000 [==============================] - 10s 279us/step - loss: 0.1122 - acc: 0.9657
Epoch 312/1000
35000/35000 [==============================] - 10s 279us/step - loss: 0.1152 - acc: 0.9635
Epoch 313/1000
35000/35000 [==============================] - 10s 280us/step - loss: 0.1021 - acc: 0.9689
Epoch 314/1000
35000/35000 [==============================] - 10s 283us/step - loss: 0.1144 - acc: 0.9651
Epoch 315/1000
35000/35000 [==============================] - 10s 282us/step - loss: 0.1110 - acc: 0.9682
Epoch 316/1000
35000/35000 [==============================] - 10s 282us/step - loss: 0.1230 - acc: 0.9640
Epoch 317/1000
35000/35000 [==============================] - 10s 277us/step - loss: 0.1100 - acc: 0.9668
Epoch 318/1000
35000/35000 [==============================] - 10s 277us/step - loss: 0.1190 - acc: 0.9630
Epoch 319/1000
35000/35000 [==============================] -

35000/35000 [==============================] - 10s 284us/step - loss: 0.1217 - acc: 0.9649
Epoch 465/1000
35000/35000 [==============================] - 10s 285us/step - loss: 0.1254 - acc: 0.9630
Epoch 466/1000
35000/35000 [==============================] - 10s 284us/step - loss: 0.1265 - acc: 0.9631
Epoch 467/1000
35000/35000 [==============================] - 10s 283us/step - loss: 0.1179 - acc: 0.9659
Epoch 468/1000
35000/35000 [==============================] - 10s 280us/step - loss: 0.1202 - acc: 0.9644
Epoch 469/1000
35000/35000 [==============================] - 10s 273us/step - loss: 0.1316 - acc: 0.9646
Epoch 470/1000
35000/35000 [==============================] - 10s 280us/step - loss: 0.1280 - acc: 0.9642
Epoch 471/1000
35000/35000 [==============================] - 10s 284us/step - loss: 0.1275 - acc: 0.9643
Epoch 472/1000
35000/35000 [==============================] - 10s 281us/step - loss: 0.1209 - acc: 0.9659
Epoch 473/1000
35000/35000 [==============================] -

35000/35000 [==============================] - 10s 286us/step - loss: 0.1341 - acc: 0.9636
Epoch 619/1000
35000/35000 [==============================] - 10s 282us/step - loss: 0.1307 - acc: 0.9646
Epoch 620/1000
35000/35000 [==============================] - 10s 280us/step - loss: 0.1368 - acc: 0.9641
Epoch 621/1000
35000/35000 [==============================] - 10s 281us/step - loss: 0.1498 - acc: 0.9586
Epoch 622/1000
35000/35000 [==============================] - 10s 279us/step - loss: 0.1353 - acc: 0.9613
Epoch 623/1000
35000/35000 [==============================] - 10s 281us/step - loss: 0.1505 - acc: 0.9577
Epoch 624/1000
35000/35000 [==============================] - 10s 281us/step - loss: 0.1468 - acc: 0.9605
Epoch 625/1000
35000/35000 [==============================] - 10s 285us/step - loss: 0.1433 - acc: 0.9630
Epoch 626/1000
35000/35000 [==============================] - 10s 282us/step - loss: 0.1373 - acc: 0.9632
Epoch 627/1000
35000/35000 [==============================] -

35000/35000 [==============================] - 10s 284us/step - loss: 0.1509 - acc: 0.9618
Epoch 773/1000
35000/35000 [==============================] - 10s 278us/step - loss: 0.1662 - acc: 0.9563
Epoch 774/1000
35000/35000 [==============================] - 10s 282us/step - loss: 0.1482 - acc: 0.9589
Epoch 775/1000
35000/35000 [==============================] - 10s 279us/step - loss: 0.1710 - acc: 0.9547
Epoch 776/1000
35000/35000 [==============================] - 10s 279us/step - loss: 0.1550 - acc: 0.9585
Epoch 777/1000
35000/35000 [==============================] - 10s 282us/step - loss: 0.1414 - acc: 0.9602
Epoch 778/1000
35000/35000 [==============================] - 10s 275us/step - loss: 0.1485 - acc: 0.9598
Epoch 779/1000
35000/35000 [==============================] - 10s 279us/step - loss: 0.1618 - acc: 0.9573
Epoch 780/1000
35000/35000 [==============================] - 10s 280us/step - loss: 0.1584 - acc: 0.9577
Epoch 781/1000
35000/35000 [==============================] -

35000/35000 [==============================] - 10s 279us/step - loss: 0.1660 - acc: 0.9583
Epoch 927/1000
35000/35000 [==============================] - 10s 273us/step - loss: 0.1650 - acc: 0.9559
Epoch 928/1000
35000/35000 [==============================] - 10s 281us/step - loss: 0.1809 - acc: 0.9524
Epoch 929/1000
35000/35000 [==============================] - 10s 279us/step - loss: 0.1605 - acc: 0.9571
Epoch 930/1000
35000/35000 [==============================] - 10s 281us/step - loss: 0.1684 - acc: 0.9567
Epoch 931/1000
35000/35000 [==============================] - 10s 282us/step - loss: 0.1759 - acc: 0.9540
Epoch 932/1000
35000/35000 [==============================] - 10s 278us/step - loss: 0.1747 - acc: 0.9521
Epoch 933/1000
35000/35000 [==============================] - 10s 273us/step - loss: 0.1855 - acc: 0.9509
Epoch 934/1000
35000/35000 [==============================] - 10s 283us/step - loss: 0.1852 - acc: 0.9525
Epoch 935/1000
35000/35000 [==============================] -

### total accuracy

In [19]:
score = model.evaluate(x_test,y_test, verbose=0)
print('loss=', score[0])
print('accuracy=',score[1])

loss= 3.1689289825439455
accuracy= 0.6244


### 개별 accuracy

In [ ]:
categories=["coat","dress","pullover","shirt","t"]
for i in range(5):
    yyy_test=[]
    xxx_test=[]
    for j in range(5000):
        if y_test[j][i]==1:
            yyy_test.append(y_test[j])
            xxx_test.append(x_test[j])
    yyy_test=np.array(yyy_test)
    xxx_test=np.array(xxx_test)
    score = model.evaluate(xxx_test,yyy_test, verbose=0)
    print(categories[i]+'의 loss=', score[0])
    print(categories[i]+'의 accuracy=',score[1])
    print('-----------------------------------')