In [3]:
from PIL import Image
import os, glob
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
from keras.models import Sequential
from keras.layers import Convolution2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
import numpy as np

Using TensorFlow backend.


In [5]:
caltech_dir="./instagram_O/2"
caltech_dirr="./instagram_O/TEST"
categories=["coat","dress","pullover","shirt","t"]
nb_classes=len(categories)

In [6]:
image_w=64 
image_h=64

### TEST 데이터 불러오기

In [7]:
xx=[]
yy=[]
for idx, cat in enumerate(categories):
    # 레이블 지정 ---4
    label=[0 for i in range(nb_classes)]
    label[idx]=1
    # 이미지 ---5
    image_dirr=caltech_dirr+"/"+cat
    files=glob.glob(image_dirr+"/*.*")
    for i, f in enumerate(files):
        img=Image.open(f) # ---6
        img=img.convert("RGB")
        img=img.resize((image_w, image_h))
        data=np.asarray(img)
        xx.append(data)
        yy.append(label)
        if i%10==0:
            print(i, "\n", data)
xx=np.array(xx)
yy=np.array(yy)

0 
 [[[ 51  46  50]
  [ 53  49  50]
  [154 149 145]
  ...
  [165 164 162]
  [189 186 181]
  [142 141 123]]

 [[ 28  25  20]
  [119 115 116]
  [ 57  51  51]
  ...
  [148 147 142]
  [169 166 161]
  [144 143 125]]

 [[124 127 108]
  [143 145 131]
  [ 61  51  50]
  ...
  [141 141 133]
  [122 122 114]
  [115 116 100]]

 ...

 [[212 208 205]
  [214 210 207]
  [220 216 215]
  ...
  [186 183 178]
  [187 182 178]
  [181 176 172]]

 [[186 179 173]
  [188 181 175]
  [186 181 177]
  ...
  [ 57  46  50]
  [ 59  48  52]
  [ 57  46  50]]

 [[ 40  38  39]
  [ 38  36  37]
  [ 43  37  37]
  ...
  [ 52  48  49]
  [ 52  48  49]
  [ 51  47  48]]]
10 
 [[[249 216 183]
  [244 214 180]
  [229 215 206]
  ...
  [222 210 194]
  [197 187 177]
  [176 189 195]]

 [[255 242 218]
  [211 198 190]
  [226 209 193]
  ...
  [215 182 149]
  [173 170 153]
  [215 214 222]]

 [[245 235 225]
  [223 215 204]
  [237 227 217]
  ...
  [197 162 130]
  [230 209 178]
  [180 192 204]]

 ...

 [[204 177 156]
  [177 160 140]
  [123 115 

### TRAIN 데이터 불러오기

In [8]:
x=[]
y=[]
for idx, cat in enumerate(categories):
    # 레이블 지정 ---4
    label=[0 for i in range(nb_classes)]
    label[idx]=1
    # 이미지 ---5
    image_dir=caltech_dir+"/"+cat
    files=glob.glob(image_dir+"/*.*")
    for i, f in enumerate(files):
        img=Image.open(f) # ---6
        img=img.convert("RGB")
        img=img.resize((image_w, image_h))
        data=np.asarray(img)
        x.append(data)
        y.append(label)
        if i%10==0:
            print(i, "\n", data)
x=np.array(x)
y=np.array(y)

0 
 [[[248 250 247]
  [242 244 241]
  [249 251 248]
  ...
  [183 166 112]
  [193 173 122]
  [200 176 128]]

 [[244 246 243]
  [246 248 245]
  [245 247 244]
  ...
  [161 142 100]
  [181 160 113]
  [194 171 119]]

 [[243 245 242]
  [245 247 244]
  [239 241 238]
  ...
  [175 172 139]
  [191 162 118]
  [187 170 118]]

 ...

 [[216 217 209]
  [201 202 194]
  [217 214 207]
  ...
  [178 145 114]
  [178 154 118]
  [126 111  68]]

 [[203 204 196]
  [212 213 205]
  [198 195 188]
  ...
  [165 149 115]
  [188 164 130]
  [143 109  74]]

 [[210 211 203]
  [196 197 189]
  [206 203 196]
  ...
  [162 156 142]
  [179 170 153]
  [180 167 150]]]
10 
 [[[ 12  12  12]
  [ 12  12  12]
  [ 13  11  12]
  ...
  [ 10  10  10]
  [ 11   9  10]
  [ 10   8   9]]

 [[ 12  12  12]
  [ 12  12  12]
  [ 14  12  13]
  ...
  [ 10  10  10]
  [ 11   9  10]
  [ 11   9  10]]

 [[ 13  11  12]
  [ 14  12  13]
  [ 15  13  14]
  ...
  [ 11   9  10]
  [ 10   8   9]
  [ 11   9  10]]

 ...

 [[237 224 169]
  [220 208 148]
  [163 152 

### 데이터 셋 분리 및 정규화

In [9]:
# 학습 전용 데이터와 테스트 전용 데이터 구분 ---101
x_train=x
x_test=xx
y_train=y
y_test=yy
xy=(x_train, x_test, y_train, y_test)
np.save("./instagram_O/5obj.npy", xy)

print("ok,", len(y))

ok, 10578


In [10]:
categories=["coat","dress","pullover","shirt","t"]
nb_classes=len(categories)
image_w=64
image_h=64

In [11]:
x_train, x_test, y_train, y_test = np.load("./instagram_O/5obj.npy", allow_pickle=True)
#데이터 정규화하기
x_train = x_train.astype("float")/255
x_test = x_test.astype("float")/255
print('x_train:', x_train.shape)
len(y_train)

x_train: (10578, 64, 64, 3)


10578

### 모델 학습(1)

In [ ]:
import keras.backend.tensorflow_backend as K
with K.tf.device('/device:GPU:2'):
    model = Sequential()
    model.add(Convolution2D(32,3,3,border_mode='same',input_shape=x_train.shape[1:]))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    #모델 훈련하기
    model.fit(x_train, y_train, batch_size=50, nb_epoch=10)

C:\Users\Park Hye Rin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(64, 64, 3..., padding="same")`
  after removing the cwd from sys.path.
C:\Users\Park Hye Rin\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
  
C:\Users\Park Hye Rin\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Park Hye Rin\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/10
10578/10578 [==============================] - 116s 11ms/step - loss: 1.3754 - acc: 0.4280
Epoch 2/10
10578/10578 [==============================] - 111s 10ms/step - loss: 0.9978 - acc: 0.6057
Epoch 3/10
10578/10578 [==============================] - 114s 11ms/step - loss: 0.8314 - acc: 0.6827
Epoch 4/10
10578/10578 [==============================] - 114s 11ms/step - loss: 0.6990 - acc: 0.7359
Epoch 5/10
10578/10578 [==============================] - 111s 10ms/step - loss: 0.6004 - acc: 0.7757
Epoch 6/10
10578/10578 [==============================] - 114s 11ms/step - loss: 0.4932 - acc: 0.8196
Epoch 7/10
10578/10578 [==============================] - 117s 11ms/step - loss: 0.4024 - acc: 0.8540
Epoch 8/10
 5900/10578 [===============>..............] - ETA: 50s - loss: 0.3244 - acc: 0.8853

### total accuracy

In [ ]:
score = model.evaluate(x_test,y_test, verbose=0)
print('loss=', score[0])
print('accuracy=',score[1])

### 개별 accuracy

In [ ]:
categories=["coat","dress","pullover","shirt","t"]
for i in range(5):
    yyy_test=[]
    xxx_test=[]
    for j in range(5000):
        if y_test[j][i]==1:
            yyy_test.append(y_test[j])
            xxx_test.append(x_test[j])
    yyy_test=np.array(yyy_test)
    xxx_test=np.array(xxx_test)
    score = model.evaluate(xxx_test,yyy_test, verbose=0)
    print(categories[i]+'의 loss=', score[0])
    print(categories[i]+'의 accuracy=',score[1])
    print('-----------------------------------')

### 모델 학습(2)

In [ ]:
import keras.backend.tensorflow_backend as K
with K.tf.device('/device:GPU:2'):
    model = Sequential()
    model.add(Convolution2D(32,3,3,border_mode='same',input_shape=x_train.shape[1:]))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    #모델 훈련하기
    model.fit(x_train, y_train, batch_size=50, nb_epoch=100)

### total accuracy

In [ ]:
score = model.evaluate(x_test,y_test, verbose=0)
print('loss=', score[0])
print('accuracy=',score[1])

### 개별 accuracy

In [ ]:
categories=["coat","dress","pullover","shirt","t"]
for i in range(5):
    yyy_test=[]
    xxx_test=[]
    for j in range(5000):
        if y_test[j][i]==1:
            yyy_test.append(y_test[j])
            xxx_test.append(x_test[j])
    yyy_test=np.array(yyy_test)
    xxx_test=np.array(xxx_test)
    score = model.evaluate(xxx_test,yyy_test, verbose=0)
    print(categories[i]+'의 loss=', score[0])
    print(categories[i]+'의 accuracy=',score[1])
    print('-----------------------------------')

### 모델 학습(3)

In [ ]:
import keras.backend.tensorflow_backend as K
with K.tf.device('/device:GPU:2'):
    model = Sequential()
    model.add(Convolution2D(32,3,3,border_mode='same',input_shape=x_train.shape[1:]))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(Convolution2D(64, 3, 3, border_mode='same'))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    #모델 훈련하기
    model.fit(x_train, y_train, batch_size=50, nb_epoch=1000)

### total accuracy

In [ ]:
score = model.evaluate(x_test,y_test, verbose=0)
print('loss=', score[0])
print('accuracy=',score[1])

### 개별 accuracy

In [ ]:
categories=["coat","dress","pullover","shirt","t"]
for i in range(5):
    yyy_test=[]
    xxx_test=[]
    for j in range(5000):
        if y_test[j][i]==1:
            yyy_test.append(y_test[j])
            xxx_test.append(x_test[j])
    yyy_test=np.array(yyy_test)
    xxx_test=np.array(xxx_test)
    score = model.evaluate(xxx_test,yyy_test, verbose=0)
    print(categories[i]+'의 loss=', score[0])
    print(categories[i]+'의 accuracy=',score[1])
    print('-----------------------------------')

### 모델 저장 및 로드

In [ ]:
hdf5_file="./instagram_O/5obj-model.hdf5"
if os.path.exists(hdf5_file):
    #기존에 학습된 모델 읽어 들이기
    model.load_weights(hdf5_file)
else:
    #학습한 모델을 파일로 저장하기
    model.fit(x_train, y_train, batch_size=256, nb_epoch=50, verbose=1)
    model.save_weights(hdf5_file)