In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# https://github.com/kaggle/docker-python
import numpy as np # linear algebra
import pandas as pd # data processing

In [20]:
from keras.utils import to_categorical
data_train = pd.read_csv('F:/instagram_data/instagram_train(b).csv')
data_test = pd.read_csv('F:/instagram_data/instagram_test(b).csv')

In [30]:
from keras.utils import to_categorical
data_train = pd.read_csv('F:/fashion_data/train_final.csv')
data_test = pd.read_csv('F:/instagram_data/instagram_test(b).csv')

In [31]:
data_train

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0          1       0       0       0       0       0       0       0       0   
1          2       0       0       0       0       0       0       0       5   
2          0       0       0       0       1       2       0       0       0   
3          3       0       0       0       0       0       0       0       0   
4          4       0       0       0       5       4       5       5       3   
5          4       0       0       0       0       0       0       0       0   
6          4       0       0       0       0       0       0       3       2   
7          0       0       0       0       0       1       0       0       0   
8          0       0       0       0       0       0       0       0       0   
9          1       0       0       0       0       1       1       0       0   
10         1       0       0       0       0       0       0       0       0   
11         3       0       0       0       0       0       0       0       0   
12         3       0       0       0       0       0       0       0       0   
13         3       0       0       0       0       0       0       0       0   
14         4       0       0       0       0       0       0       0       0   
15         4       0       0       0       0       0       1       0       1   
16         0       0       0       0       0       0       0       0       0   
17         4       0       0       0       0       2       0       0       0   
18         4       0       0       0       0       0       0       0       1   
19         0       0       0       0       0       0       0       0       0   
20         3       0       0       0       0       0       0       0       0   
21         1       0       0       0       0       0       0       0       0   
22         3       0       0       0       0       0       0       0       0   
23         4       0       0       0       0       0       0       0       0   
24         1       0       0       0       0       0       0       0       0   
25         2       0       0       0       0       0       0       0       0   
26         0       0       0       0       0       0       0       2      23   
27         2       0       0       0       0       0       0       0       0   
28         0       0       0       0       0       0       1       1       0   
29         2       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
29970      2       0       0       0       0       0       0       0       2   
29971      2       0       0       0       0       0       0       1       0   
29972      1       0       0       0       0       0       0       0       1   
29973      3       0       0       0       0       0       0       0       0   
29974      1       0       0       0       0       0       0       1       1   
29975      2       0       0       0       0       0       0       0       0   
29976      3       0       0       0       0       0       0       0       0   
29977      0       0       0       0       0       0       0       0       0   
29978      2       0       0       0       0       0       0       0       0   
29979      4       0       0       0       0       0       0       0       0   
29980      2       0       0       0       0       0       0       0       0   
29981      2       0       0       0       0       0       0       0       0   
29982      2       0       0       0       0       0       0       0       0   
29983      3       0       0       0       0       0       1       0       0   
29984      4       0       0       0       0       0       0       0       0   
29985      1       0       0       0       0       0       0       0       0   
29986      0       0       0       0       0       0       0       0       0   
29987      3       0       0       0       0       0       0       0       0   
29988  

In [32]:
X_train = np.array(data_train.iloc[:, 1:])
X_test = np.array(data_test.iloc[:, 1:])
y_train = to_categorical(np.array(data_train.iloc[:, 0]))
y_test = to_categorical(np.array(data_test.iloc[:, 0]))

In [33]:
img_rows, img_cols = 28, 28
X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [34]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Flatten, Conv2D, MaxPooling2D

input_shape = (img_rows, img_cols, 1)
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(250, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(5, activation='softmax'))
model.compile(optimizer='adam',
          loss='categorical_crossentropy',
          metrics=['accuracy'])

In [35]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
dropout_10 (Dropout)         (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
dropout_11 (Dropout)         (None, 5, 5, 64)          0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 1600)              0         
__________

In [ ]:
#패션미니스트 훈련

In [36]:
model.fit(X_train, y_train,
          batch_size=50,
          epochs=50,
          verbose=1,
          validation_data=(X_test, y_test))
score = model.evaluate(X_test, y_test, verbose=0)

Train on 30000 samples, validate on 5000 samples
Epoch 1/50
30000/30000 [==============================] - 37s 1ms/step - loss: 0.8111 - acc: 0.6718 - val_loss: 1.9180 - val_acc: 0.2142
Epoch 2/50
30000/30000 [==============================] - 43s 1ms/step - loss: 0.5804 - acc: 0.7773 - val_loss: 1.9590 - val_acc: 0.2176
Epoch 3/50
30000/30000 [==============================] - 37s 1ms/step - loss: 0.5230 - acc: 0.8018 - val_loss: 1.8751 - val_acc: 0.2246
Epoch 4/50
30000/30000 [==============================] - 39s 1ms/step - loss: 0.4895 - acc: 0.8120 - val_loss: 2.0409 - val_acc: 0.2194s - loss: 
Epoch 5/50
30000/30000 [==============================] - 38s 1ms/step - loss: 0.4645 - acc: 0.8221 - val_loss: 2.0518 - val_acc: 0.2282
Epoch 6/50
30000/30000 [==============================] - 38s 1ms/step - loss: 0.4466 - acc: 0.8306 - val_loss: 1.9638 - val_acc: 0.2372
Epoch 7/50
30000/30000 [==============================] - 38s 1ms/step - loss: 0.4307 - acc: 0.8348 - val_loss: 2.0891 

In [37]:
print('accuracy: ',score[1])
print('loss: ',score[0])

accuracy:  0.2448
loss:  3.2238081901550295


In [ ]:
#인스타 훈련

In [28]:
model.fit(X_train, y_train,
          batch_size=50,
          epochs=50,
          verbose=1,
          validation_data=(X_test, y_test))
score = model.evaluate(X_test, y_test, verbose=0)

Train on 30000 samples, validate on 5000 samples
Epoch 1/50
30000/30000 [==============================] - 34s 1ms/step - loss: 1.1366 - acc: 0.5430 - val_loss: 1.4355 - val_acc: 0.3918
Epoch 2/50
30000/30000 [==============================] - 36s 1ms/step - loss: 1.1180 - acc: 0.5511 - val_loss: 1.4551 - val_acc: 0.3866
Epoch 3/50
30000/30000 [==============================] - 35s 1ms/step - loss: 1.1008 - acc: 0.5597 - val_loss: 1.4364 - val_acc: 0.4028
Epoch 4/50
30000/30000 [==============================] - 36s 1ms/step - loss: 1.0776 - acc: 0.5674 - val_loss: 1.4661 - val_acc: 0.3986
Epoch 5/50
30000/30000 [==============================] - 37s 1ms/step - loss: 1.0644 - acc: 0.5729 - val_loss: 1.4845 - val_acc: 0.3934
Epoch 6/50
30000/30000 [==============================] - 37s 1ms/step - loss: 1.0341 - acc: 0.5868 - val_loss: 1.4808 - val_acc: 0.3926
Epoch 7/50
30000/30000 [==============================] - 38s 1ms/step - loss: 1.0224 - acc: 0.5896 - val_loss: 1.4536 - val_acc:

In [29]:
print('accuracy: ',score[1])
print('loss: ',score[0])

accuracy:  0.4308
loss:  1.5973678594589233


In [ ]:
#모델 저장하기

In [31]:
import os, glob

In [34]:
hdf5_file="./image/4obj-model.hdf5"
if os.path.exists(hdf5_file):
    #기존에 학습된 모델 읽어 들이기
    model.load_weights(hdf5_file)
else:
    #학습한 모델을 파일로 저장하기
    model.fit(X_train, y_train, batch_size=32, nb_epoch=10)
    model.save_weights(hdf5_file)

Epoch 1/10
   96/30000 [..............................] - ETA: 38s - loss: 0.6539 - acc: 0.7604

C:\Users\Park Hye Rin\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  import sys


30000/30000 [==============================] - 36s 1ms/step - loss: 0.3942 - acc: 0.8501
Epoch 2/10
30000/30000 [==============================] - 37s 1ms/step - loss: 0.3816 - acc: 0.8525
Epoch 3/10
30000/30000 [==============================] - 38s 1ms/step - loss: 0.3711 - acc: 0.8588
Epoch 4/10
30000/30000 [==============================] - 37s 1ms/step - loss: 0.3679 - acc: 0.8599
Epoch 5/10
30000/30000 [==============================] - 37s 1ms/step - loss: 0.3572 - acc: 0.8627
Epoch 6/10
30000/30000 [==============================] - 38s 1ms/step - loss: 0.3526 - acc: 0.8635
Epoch 7/10
30000/30000 [==============================] - 38s 1ms/step - loss: 0.3436 - acc: 0.8668
Epoch 8/10
30000/30000 [==============================] - 38s 1ms/step - loss: 0.3349 - acc: 0.8705
Epoch 9/10
30000/30000 [==============================] - 38s 1ms/step - loss: 0.3299 - acc: 0.8738
Epoch 10/10
30000/30000 [==============================] - 40s 1ms/step - loss: 0.3290 - acc: 0.8739


In [35]:
#테스트 데이터 불러오기

In [36]:
from PIL import Image
import os, glob
import numpy as np
from sklearn.model_selection import train_test_split

In [37]:
from keras.models import Sequential
from keras.layers import Convolution2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
import numpy as np

In [38]:
# 분류 대상 카테고리 선택하기 ---101
caltech_dir="./instagram_O/TEST"
categories=["coat","dress","pullover","t","shirt"]
nb_classes=len(categories)

In [39]:
# 이미지 크기 지정 ---2
image_w=64
image_h=64
pixels=image_w*image_h*3

In [41]:
# 이미지 데이터 읽어 들이기 ---3
x=[]
y=[]
for idx, cat in enumerate(categories):
    # 레이블 지정 ---4
    label=[0 for i in range(nb_classes)]
    label[idx]=1
    # 이미지 ---5
    image_dir=caltech_dir+"/"+cat
    files=glob.glob(image_dir+"/*.*")
    for i, f in enumerate(files):
        img=Image.open(f) # ---6
        img=img.convert("RGB")
        img=img.resize((image_w, image_h))
        data=np.asarray(img)
        x.append(data)
        y.append(label)
        if i%10==0:
            print(i, "\n", data)
x=np.array(x)
y=np.array(y)

0 
 [[[208 201 195]
  [208 201 195]
  [205 198 192]
  ...
  [199 190 181]
  [203 196 190]
  [202 195 189]]

 [[205 198 192]
  [204 197 191]
  [206 199 193]
  ...
  [199 190 181]
  [203 196 190]
  [207 200 194]]

 [[206 197 190]
  [206 197 190]
  [205 196 189]
  ...
  [202 193 186]
  [203 196 190]
  [205 198 192]]

 ...

 [[163 147 132]
  [172 156 141]
  [170 156 143]
  ...
  [164 148 135]
  [165 149 136]
  [167 151 138]]

 [[167 151 136]
  [172 156 141]
  [171 155 140]
  ...
  [166 150 137]
  [166 150 135]
  [166 150 135]]

 [[169 153 138]
  [171 155 140]
  [168 152 137]
  ...
  [165 149 136]
  [167 151 136]
  [166 150 135]]]
10 
 [[[207 184 153]
  [207 184 153]
  [207 184 153]
  ...
  [104  75  59]
  [ 95  65  41]
  [ 90  63  42]]

 [[207 184 153]
  [208 185 154]
  [210 187 156]
  ...
  [103  75  54]
  [ 98  67  47]
  [ 90  63  46]]

 [[208 184 156]
  [208 184 156]
  [210 186 158]
  ...
  [105  77  55]
  [ 95  64  44]
  [ 89  62  45]]

 ...

 [[246 237 220]
  [249 238 218]
  [245 232 

140 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
150 
 [[[188 179 164]
  [204 195 180]
  [204 195 178]
  ...
  [254 253 248]
  [252 253 239]
  [255 252 235]]

 [[183 174 159]
  [220 211 196]
  [219 210 193]
  ...
  [243 242 237]
  [234 226 215]
  [219 207 193]]

 [[189 179 167]
  [167 157 145]
  [195 186 169]
  ...
  [220 217 208]
  [220 213 197]
  [209 202 186]]

 ...

 [[123 120 105]
  [ 13 100 171]
  [  4  

280 
 [[[144 127 101]
  [157 146 124]
  [147 131 106]
  ...
  [247 247 247]
  [247 247 247]
  [247 247 247]]

 [[128 111  85]
  [165 154 132]
  [154 138 113]
  ...
  [247 247 247]
  [247 247 247]
  [247 247 247]]

 [[136 119  91]
  [171 160 138]
  [152 138 111]
  ...
  [247 247 247]
  [247 247 247]
  [247 247 247]]

 ...

 [[124 116  93]
  [144 137 118]
  [ 88  61  40]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[122 110  86]
  [113  98  77]
  [141 126 107]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[123 115  94]
  [ 76  65  47]
  [128 117  97]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
290 
 [[[241 242 244]
  [241 242 244]
  [240 241 243]
  ...
  [236 237 239]
  [236 237 239]
  [232 238 238]]

 [[240 241 243]
  [240 241 243]
  [240 241 243]
  ...
  [236 237 239]
  [236 237 239]
  [232 238 238]]

 [[239 240 242]
  [239 240 242]
  [239 240 242]
  ...
  [235 239 240]
  [236 237 239]
  [236 237 239]]

 ...

 [[247 248 252]
  [247 248 252]
  [247 2

420 
 [[[173 174 160]
  [173 174 160]
  [173 174 160]
  ...
  [173 174 160]
  [173 174 160]
  [173 174 160]]

 [[173 174 160]
  [173 174 160]
  [173 174 160]
  ...
  [173 174 160]
  [173 174 160]
  [173 174 160]]

 [[173 174 160]
  [173 174 160]
  [173 174 160]
  ...
  [173 174 160]
  [173 174 160]
  [173 174 160]]

 ...

 [[173 174 160]
  [173 174 160]
  [173 174 160]
  ...
  [173 174 160]
  [173 174 160]
  [173 174 160]]

 [[173 174 160]
  [173 174 160]
  [173 174 160]
  ...
  [173 174 160]
  [173 174 160]
  [173 174 160]]

 [[173 174 160]
  [173 174 160]
  [173 174 160]
  ...
  [173 174 160]
  [173 174 160]
  [173 174 160]]]
430 
 [[[243 252 251]
  [248 252 253]
  [248 254 254]
  ...
  [253 254 255]
  [253 254 255]
  [253 254 255]]

 [[246 255 254]
  [250 254 255]
  [248 254 254]
  ...
  [253 254 255]
  [253 254 255]
  [253 254 255]]

 [[247 248 250]
  [249 250 255]
  [245 250 254]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 ...

 [[156 159 130]
  [159 162 135]
  [155 1

560 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
570 
 [[[ 81  82  76]
  [ 80  81  75]
  [ 77  78  72]
  ...
  [227 227 219]
  [225 225 217]
  [226 226 218]]

 [[ 81  82  76]
  [ 77  78  72]
  [ 74  75  69]
  ...
  [225 225 217]
  [224 224 212]
  [227 227 215]]

 [[ 77  78  72]
  [ 76  77  71]
  [ 73  74  68]
  ...
  [226 226 214]
  [228 226 214]
  [228 226 214]]

 ...

 [[ 94  97  90]
  [100 103  96]
  [ 79  

700 
 [[[226 221 225]
  [210 194 169]
  [212 194 170]
  ...
  [211 210 205]
  [211 208 201]
  [206 199 189]]

 [[224 220 221]
  [213 196 178]
  [209 192 164]
  ...
  [211 210 205]
  [208 208 198]
  [207 194 175]]

 [[219 214 208]
  [215 198 182]
  [211 194 164]
  ...
  [213 210 205]
  [212 208 199]
  [212 194 182]]

 ...

 [[ 84  64  14]
  [ 87  67  17]
  [117  98  66]
  ...
  [199 202 211]
  [199 204 208]
  [186 190 199]]

 [[105  90  47]
  [106  91  48]
  [104  89  46]
  ...
  [202 202 210]
  [203 202 208]
  [190 193 202]]

 [[125 110  67]
  [119 104  61]
  [122 107  64]
  ...
  [202 202 210]
  [202 201 207]
  [186 189 198]]]
710 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

840 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
850 
 [[[177 172 168]
  [177 172 168]
  [178 173 169]
  ...
  [173 172 170]
  [173 172 168]
  [173 172 168]]

 [[ 25  15  13]
  [ 25  15  13]
  [157 152 148]
  ...
  [174 173 171]
  [173 172 168]
  [173 172 168]]

 [[ 29  19  20]
  [ 25  15  16]
  [ 27  19  16]
  ...
  [174 173 171]
  [173 172 168]
  [172 171 167]]

 ...

 [[195 177 167]
  [193 175 165]
  [192 1

980 
 [[[244 243 248]
  [244 243 248]
  [244 243 248]
  ...
  [227 218 221]
  [229 218 222]
  [228 217 221]]

 [[244 243 248]
  [244 243 248]
  [244 243 248]
  ...
  [227 218 221]
  [225 219 221]
  [224 218 220]]

 [[244 243 248]
  [244 243 248]
  [244 243 248]
  ...
  [227 218 221]
  [227 218 221]
  [225 216 219]]

 ...

 [[218 207 213]
  [218 207 213]
  [213 206 213]
  ...
  [190 174 174]
  [193 177 177]
  [193 177 177]]

 [[215 206 211]
  [215 206 211]
  [214 204 212]
  ...
  [190 174 174]
  [191 175 176]
  [192 177 174]]

 [[214 205 210]
  [214 205 210]
  [212 202 210]
  ...
  [191 175 175]
  [191 175 176]
  [194 179 176]]]
990 
 [[[151 147 146]
  [150 149 147]
  [153 152 150]
  ...
  [ 67  57  48]
  [ 66  56  46]
  [ 68  54  45]]

 [[151 147 146]
  [153 152 150]
  [152 151 149]
  ...
  [ 63  56  46]
  [ 62  56  44]
  [ 61  51  41]]

 [[153 149 148]
  [152 151 149]
  [152 151 149]
  ...
  [ 60  51  42]
  [ 56  49  39]
  [ 60  50  41]]

 ...

 [[122 118 117]
  [114 113 111]
  [101 1

120 
 [[[116 111 105]
  [114 109 103]
  [110 106  95]
  ...
  [  9   3   5]
  [113 145 204]
  [105 153 215]]

 [[115 110 104]
  [115 110 104]
  [112 108  97]
  ...
  [161 183 224]
  [107 157 206]
  [108 153 220]]

 [[117 112 106]
  [114 109 103]
  [112 108  97]
  ...
  [102 157 222]
  [109 157 223]
  [109 157 223]]

 ...

 [[ 73  74  69]
  [136 132 129]
  [132 128 127]
  ...
  [255 249 241]
  [234 230 219]
  [213 209 198]]

 [[ 76  76  74]
  [135 132 127]
  [138 130 128]
  ...
  [ 91  58  49]
  [214 208 196]
  [140 133 125]]

 [[ 78  78  76]
  [142 139 134]
  [139 131 129]
  ...
  [ 96  59  51]
  [ 98  70  66]
  [218 211 203]]]
130 
 [[[220 212 209]
  [230 222 219]
  [243 240 235]
  ...
  [234 227 234]
  [235 229 233]
  [221 219 222]]

 [[215 207 204]
  [222 214 211]
  [223 215 212]
  ...
  [236 229 236]
  [230 224 228]
  [255 254 255]]

 [[215 207 204]
  [220 212 209]
  [226 223 218]
  ...
  [232 225 232]
  [231 224 231]
  [ 38  36  37]]

 ...

 [[216 206 196]
  [215 202 193]
  [215 2

260 
 [[[200 184 169]
  [201 188 172]
  [184 168 153]
  ...
  [ 42  52  41]
  [ 29  39  31]
  [ 61  75  58]]

 [[199 183 168]
  [201 188 172]
  [183 167 152]
  ...
  [ 37  47  36]
  [ 37  47  39]
  [ 48  62  45]]

 [[195 179 164]
  [202 186 171]
  [180 168 152]
  ...
  [ 52  63  49]
  [ 48  59  45]
  [ 47  57  48]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
270 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

390 
 [[[202 183 169]
  [204 188 173]
  [207 191 175]
  ...
  [226 213 197]
  [216 205 187]
  [223 212 194]]

 [[199 183 168]
  [200 188 172]
  [207 191 175]
  ...
  [219 206 190]
  [211 200 182]
  [225 214 196]]

 [[197 181 165]
  [204 188 172]
  [209 193 178]
  ...
  [220 207 191]
  [213 205 186]
  [220 212 193]]

 ...

 [[ 94  63  42]
  [ 94  63  42]
  [108  73  53]
  ...
  [179 129 104]
  [165 117  81]
  [187 132  91]]

 [[ 94  59  39]
  [ 98  60  37]
  [116  79  52]
  ...
  [152 107  78]
  [174 119  80]
  [181 127  83]]

 [[111  73  50]
  [114  72  47]
  [ 76  44  29]
  ...
  [150 105  76]
  [189 134  95]
  [196 142  98]]]
400 
 [[[ 75 100 105]
  [129 142 112]
  [135 140 108]
  ...
  [ 40  40  30]
  [ 45  45  35]
  [ 89  85  76]]

 [[ 73  91  91]
  [129 136 102]
  [132 137 105]
  ...
  [ 38  38  26]
  [ 46  49  38]
  [ 37  37  27]]

 [[119 127 104]
  [134 140 106]
  [119 121  99]
  ...
  [ 40  36  25]
  [ 50  50  38]
  [ 50  50  38]]

 ...

 [[128 163 130]
  [112 110 111]
  [ 99  

520 
 [[[216 212 211]
  [184 180 179]
  [195 194 192]
  ...
  [ 50  52  28]
  [ 85  89  72]
  [ 62  57  51]]

 [[186 183 178]
  [190 187 182]
  [189 188 186]
  ...
  [ 27  25   4]
  [ 72  71  50]
  [ 37  27  17]]

 [[192 187 183]
  [174 170 169]
  [159 158 156]
  ...
  [ 31  31   7]
  [ 47  47  19]
  [ 44  36  13]]

 ...

 [[ 80  71  56]
  [147 139 128]
  [139 131 120]
  ...
  [176 172 163]
  [218 214 205]
  [183 179 170]]

 [[174 166 155]
  [173 165 154]
  [148 140 129]
  ...
  [183 182 177]
  [216 215 210]
  [208 207 202]]

 [[233 225 214]
  [177 169 158]
  [158 150 139]
  ...
  [198 194 185]
  [199 195 186]
  [234 230 221]]]
530 
 [[[ 20  21  15]
  [ 19  16  11]
  [ 15   7   4]
  ...
  [ 23  23  21]
  [ 25  25  23]
  [115 115 113]]

 [[ 21  22  16]
  [ 20  17  12]
  [ 16   8   5]
  ...
  [ 23  23  21]
  [ 27  27  25]
  [132 132 130]]

 [[ 20  19  15]
  [ 22  21  17]
  [ 12   8   5]
  ...
  [ 23  23  21]
  [ 36  36  34]
  [183 183 181]]

 ...

 [[157 145 133]
  [154 142 130]
  [154 1

650 
 [[[189 182 174]
  [188 181 173]
  [188 184 175]
  ...
  [ 44  36  33]
  [ 47  47  45]
  [ 53  53  55]]

 [[184 181 172]
  [186 183 174]
  [188 184 175]
  ...
  [117 109 106]
  [ 40  40  38]
  [ 45  45  47]]

 [[187 182 176]
  [186 181 175]
  [187 182 176]
  ...
  [ 44  40  39]
  [ 38  38  38]
  [ 45  45  45]]

 ...

 [[ 76  44  21]
  [ 57  31  14]
  [100  60  34]
  ...
  [ 96  53  21]
  [ 41  24  16]
  [ 36  32  21]]

 [[ 84  57  36]
  [ 76  50  25]
  [ 83  47  25]
  ...
  [ 91  56  28]
  [ 50  20   0]
  [ 32  31  29]]

 [[ 99  65  37]
  [ 72  46  29]
  [ 84  48  26]
  ...
  [ 82  55  28]
  [ 67  40  13]
  [ 34  27  17]]]
660 
 [[[234 233 229]
  [226 225 221]
  [223 222 220]
  ...
  [168 165 160]
  [165 162 157]
  [163 160 155]]

 [[234 233 229]
  [222 221 217]
  [220 219 217]
  ...
  [165 162 157]
  [165 162 157]
  [163 160 155]]

 [[234 233 229]
  [226 225 221]
  [222 221 217]
  ...
  [169 166 161]
  [166 163 158]
  [163 160 155]]

 ...

 [[241 240 236]
  [239 238 234]
  [237 2

780 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
790 
 [[[215 190 160]
  [217 192 162]
  [218 195 164]
  ...
  [223 206 178]
  [223 206 178]
  [223 206 178]]

 [[215 190 160]
  [216 191 161]
  [217 194 163]
  ...
  [225 208 180]
  [225 208 180]
  [223 206 178]]

 [[215 190 159]
  [218 193 162]
  [220 195 164]
  ...
  [227 206 179]
  [229 205 179]
  [225 205 178]]

 ...

 [[212 185 158]
  [210 183 156]
  [213 1

910 
 [[[ 24  64  53]
  [ 13  38  32]
  [  4  17  10]
  ...
  [ 34  24  25]
  [123 122 136]
  [ 94  89  96]]

 [[  3  16   9]
  [  6  15  10]
  [ 15  20  16]
  ...
  [225 207 207]
  [ 56  26  28]
  [ 41  19  22]]

 [[ 11  16  12]
  [  6  11   7]
  [  4   5   7]
  ...
  [ 40  30  28]
  [ 78  75  82]
  [123 127 138]]

 ...

 [[190 178 164]
  [136 124 112]
  [121 109  97]
  ...
  [189 167 143]
  [227 205 181]
  [239 221 199]]

 [[ 68  55  39]
  [218 206 194]
  [ 25  11   0]
  ...
  [216 199 183]
  [221 199 175]
  [177 155 132]]

 [[224 210 199]
  [240 227 219]
  [164 152 136]
  ...
  [236 215 188]
  [188 167 140]
  [ 57  35  11]]]
920 
 [[[233 224 217]
  [226 219 209]
  [220 213 203]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[248 239 232]
  [226 219 209]
  [224 217 207]
  ...
  [254 254 254]
  [255 255 255]
  [255 255 255]]

 [[255 251 245]
  [235 224 220]
  [224 217 207]
  ...
  [254 254 254]
  [255 255 255]
  [255 255 255]]

 ...

 [[231 229 230]
  [233 231 232]
  [227 2

40 
 [[[235 209 148]
  [230 204 143]
  [227 198 138]
  ...
  [211 204 178]
  [215 207 186]
  [222 214 193]]

 [[235 209 148]
  [231 205 144]
  [227 198 138]
  ...
  [207 200 172]
  [204 199 169]
  [208 203 173]]

 [[125 120 116]
  [203 196 186]
  [117 109 107]
  ...
  [202 196 162]
  [211 202 169]
  [209 200 167]]

 ...

 [[228 201 190]
  [223 194 176]
  [226 191 169]
  ...
  [188 157 129]
  [188 158 132]
  [190 156 131]]

 [[227 199 187]
  [226 193 176]
  [222 188 163]
  ...
  [185 154 126]
  [183 156 129]
  [188 152 128]]

 [[223 196 179]
  [226 194 173]
  [216 182 157]
  ...
  [181 150 122]
  [176 149 119]
  [181 146 118]]]
50 
 [[[ 32  42  34]
  [ 29  39  31]
  [ 42  49  42]
  ...
  [131 128 123]
  [127 123 114]
  [123 119 110]]

 [[ 17  26  21]
  [ 31  40  35]
  [ 43  50  43]
  ...
  [ 40  44  47]
  [ 36  37  42]
  [ 30  31  36]]

 [[ 55  61  57]
  [ 46  52  48]
  [ 35  41  37]
  ...
  [ 53  59  59]
  [ 50  55  58]
  [ 58  63  66]]

 ...

 [[166 154 140]
  [181 169 155]
  [173 161

180 
 [[[187 201 212]
  [185 199 210]
  [182 196 196]
  ...
  [199 205 201]
  [198 207 204]
  [197 206 203]]

 [[200 201 193]
  [205 206 198]
  [201 204 193]
  ...
  [206 211 191]
  [203 207 190]
  [201 205 188]]

 [[210 214 200]
  [209 213 199]
  [204 208 194]
  ...
  [208 210 196]
  [205 207 193]
  [205 207 193]]

 ...

 [[158 150 131]
  [161 153 134]
  [161 154 135]
  ...
  [159 144 125]
  [154 141 122]
  [160 147 128]]

 [[152 140 124]
  [152 140 124]
  [152 141 121]
  ...
  [161 146 123]
  [151 138 122]
  [155 143 121]]

 [[155 144 124]
  [153 142 122]
  [151 140 120]
  ...
  [159 144 121]
  [157 149 126]
  [153 145 126]]]
190 
 [[[221 203 181]
  [223 205 183]
  [225 207 183]
  ...
  [182 184 181]
  [213 217 220]
  [252 252 252]]

 [[222 204 182]
  [224 206 184]
  [221 203 183]
  ...
  [217 228 232]
  [243 247 250]
  [255 255 255]]

 [[222 205 185]
  [216 200 177]
  [219 202 184]
  ...
  [233 241 244]
  [247 252 255]
  [252 254 253]]

 ...

 [[131  95  69]
  [127  92  64]
  [126  

310 
 [[[ 32  19   2]
  [195 186 181]
  [197 182 175]
  ...
  [213 201 201]
  [208 191 183]
  [210 193 185]]

 [[ 56  39  19]
  [202 184 172]
  [198 184 175]
  ...
  [215 203 203]
  [207 190 182]
  [208 191 183]]

 [[ 56  39  21]
  [169 144 137]
  [195 180 173]
  ...
  [215 201 201]
  [202 192 182]
  [204 194 184]]

 ...

 [[190 199 208]
  [190 197 205]
  [177 172 169]
  ...
  [248 229 214]
  [248 229 215]
  [251 232 218]]

 [[167 181 194]
  [173 182 197]
  [205 200 204]
  ...
  [253 234 217]
  [244 225 210]
  [247 228 213]]

 [[165 179 192]
  [166 175 190]
  [181 180 186]
  ...
  [250 227 211]
  [248 229 214]
  [250 231 216]]]
320 
 [[[199 196 189]
  [199 196 189]
  [199 196 189]
  ...
  [182 177 173]
  [182 179 174]
  [184 181 176]]

 [[199 196 189]
  [199 196 189]
  [199 196 189]
  ...
  [182 177 173]
  [181 178 173]
  [182 179 174]]

 [[199 196 189]
  [199 196 189]
  [199 196 189]
  ...
  [179 174 170]
  [179 176 171]
  [181 178 173]]

 ...

 [[168 169 164]
  [172 173 168]
  [179 1

440 
 [[[ 59  59  61]
  [ 61  61  63]
  [ 59  58  63]
  ...
  [ 60  58  61]
  [ 60  58  61]
  [ 60  58  61]]

 [[ 60  60  62]
  [ 65  65  67]
  [ 57  56  61]
  ...
  [ 65  65  67]
  [ 73  71  74]
  [ 67  65  68]]

 [[ 62  62  64]
  [ 64  64  66]
  [ 57  57  59]
  ...
  [ 55  54  60]
  [ 52  51  56]
  [ 58  57  62]]

 ...

 [[107 120 128]
  [ 98 111 119]
  [ 99 112 120]
  ...
  [ 53  74  91]
  [ 59  72  91]
  [ 39  60  77]]

 [[113 126 134]
  [118 131 139]
  [123 136 145]
  ...
  [107 117 127]
  [118 126 137]
  [114 122 133]]

 [[116 129 137]
  [119 132 140]
  [119 132 141]
  ...
  [104 114 124]
  [120 128 139]
  [115 123 134]]]
450 
 [[[255 255 255]
  [255 255 255]
  [131 119 119]
  ...
  [183 170 164]
  [177 166 162]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [133 121 121]
  ...
  [182 169 163]
  [178 167 163]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [131 123 121]
  ...
  [197 187 185]
  [171 162 157]
  [254 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [250 2

580 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [252 253 235]
  [248 250 239]
  [254 254 254]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [226 232 158]
  [241 242 237]
  [254 254 252]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [176 183 115]
  [253 254 240]
  [205 208 165]]

 ...

 [[161 150 130]
  [165 154 134]
  [156 145 127]
  ...
  [173 164 147]
  [169 157 141]
  [163 151 135]]

 [[152 141 121]
  [151 140 120]
  [155 144 126]
  ...
  [156 147 130]
  [160 152 133]
  [154 145 130]]

 [[161 150 130]
  [153 142 122]
  [148 137 119]
  ...
  [162 153 136]
  [153 145 126]
  [163 154 139]]]
590 
 [[[126 103 109]
  [144 121 127]
  [173 151 154]
  ...
  [194 180 167]
  [194 178 165]
  [195 184 166]]

 [[205 182 188]
  [186 163 169]
  [123 101 104]
  ...
  [188 174 163]
  [189 180 165]
  [196 180 164]]

 [[148 125 131]
  [174 151 157]
  [170 148 151]
  ...
  [194 180 169]
  [193 179 166]
  [182 169 152]]

 ...

 [[170 168 169]
  [141 139 140]
  [152 1

720 
 [[[ 72  50  36]
  [155 139 124]
  [107  92  95]
  ...
  [ 34  79 146]
  [ 46  88 164]
  [ 52  97 178]]

 [[ 76  48  47]
  [154 132 134]
  [102  89  81]
  ...
  [ 49  95 157]
  [ 27  74 130]
  [ 49 104 184]]

 [[ 57  26  21]
  [140 133 127]
  [108  88  79]
  ...
  [  0   4  20]
  [  7  11  20]
  [ 71 109 190]]

 ...

 [[ 63  82 141]
  [ 73  98 152]
  [ 89 121 178]
  ...
  [117 108 137]
  [133 124 151]
  [105 115 164]]

 [[100 129 187]
  [ 60  92 153]
  [ 74 100 159]
  ...
  [108  92 129]
  [128 128 156]
  [103 113 166]]

 [[ 71  96 152]
  [ 99 115 177]
  [ 56  80 140]
  ...
  [121 115 141]
  [104 104 142]
  [ 89 100 154]]]
730 
 [[[232 234 231]
  [ 62  72  64]
  [ 45  51  47]
  ...
  [  7  10   3]
  [ 11  15  14]
  [ 67  50  32]]

 [[ 89  96  89]
  [ 42  56  43]
  [ 54  65  59]
  ...
  [ 13  14   8]
  [ 15  18  11]
  [ 10  15   9]]

 [[162 168 164]
  [103  93  83]
  [ 41  46  40]
  ...
  [ 48  53  21]
  [  8  13   6]
  [  8  13   6]]

 ...

 [[ 67  75  51]
  [116 134  76]
  [ 77  

850 
 [[[180 181 173]
  [178 179 171]
  [175 176 168]
  ...
  [158 156 143]
  [160 158 145]
  [160 158 145]]

 [[177 179 166]
  [175 177 164]
  [171 172 164]
  ...
  [157 155 142]
  [155 153 140]
  [159 157 144]]

 [[171 173 160]
  [169 171 158]
  [166 168 155]
  ...
  [154 152 139]
  [149 150 136]
  [157 153 141]]

 ...

 [[102  87  66]
  [109  95  69]
  [104  90  63]
  ...
  [ 20  22  21]
  [104  90  61]
  [ 96  85  67]]

 [[100  89  67]
  [106  92  65]
  [112  96  70]
  ...
  [ 17  16  11]
  [101  86  67]
  [ 95  85  60]]

 [[ 96  85  63]
  [103  89  62]
  [106  90  64]
  ...
  [  9   9   0]
  [114 100  73]
  [ 99  88  68]]]
860 
 [[[222 218 209]
  [224 220 211]
  [218 214 202]
  ...
  [220 217 212]
  [227 224 219]
  [217 214 209]]

 [[113 108 104]
  [220 215 211]
  [226 221 218]
  ...
  [216 213 208]
  [227 224 219]
  [211 208 203]]

 [[233 232 227]
  [188 187 182]
  [202 197 191]
  ...
  [202 199 194]
  [219 216 211]
  [253 250 245]]

 ...

 [[150 146 137]
  [158 154 145]
  [179 1

990 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
0 
 [[[117 167 220]
  [116 166 219]
  [116 166 219]
  ...
  [165 200 232]
  [167 202 232]
  [168 203 233]]

 [[116 166 219]
  [116 166 219]
  [116 166 219]
  ...
  [165 200 232]
  [166 201 231]
  [168 203 233]]

 [[116 166 219]
  [116 166 219]
  [116 166 219]
  ...
  [163 199 233]
  [165 200 230]
  [166 201 231]]

 ...

 [[ 96  95  38]
  [112 116  57]
  [117 110

120 
 [[[216 215 220]
  [217 216 221]
  [217 218 222]
  ...
  [ 24  24  26]
  [ 24  24  26]
  [ 18  18  20]]

 [[217 216 221]
  [216 215 220]
  [215 216 220]
  ...
  [ 59  59  59]
  [ 26  26  24]
  [ 19  19  17]]

 [[217 216 221]
  [217 216 221]
  [217 218 222]
  ...
  [216 212 209]
  [224 223 218]
  [216 215 210]]

 ...

 [[ 12  13  15]
  [ 12  13  15]
  [ 18  19  23]
  ...
  [ 62  62  62]
  [ 54  55  50]
  [ 59  60  55]]

 [[ 11  12  16]
  [ 12  13  17]
  [ 16  17  22]
  ...
  [ 47  48  50]
  [ 70  69  67]
  [ 58  57  55]]

 [[ 11  12  16]
  [ 12  13  17]
  [ 18  19  24]
  ...
  [178 177 175]
  [208 203 199]
  [179 174 170]]]
130 
 [[[ 38  56  30]
  [ 32  52  27]
  [197 243 255]
  ...
  [ 24  47  19]
  [ 32  57  35]
  [ 18  32   7]]

 [[ 82  81  79]
  [ 47  44  55]
  [119 121 116]
  ...
  [ 27  50  22]
  [ 58  83  53]
  [ 41  54  24]]

 [[ 39  37  42]
  [ 47  46  54]
  [ 58  57  62]
  ...
  [ 24  50   3]
  [ 39  66  21]
  [ 33  63   9]]

 ...

 [[255 248 192]
  [253 247 189]
  [166 1

260 
 [[[162 130  92]
  [165 132  97]
  [172 139 106]
  ...
  [185 152 117]
  [180 146 111]
  [180 148 110]]

 [[165 132  97]
  [170 137 104]
  [174 141 108]
  ...
  [176 143 108]
  [180 146 111]
  [186 154 116]]

 [[166 136 102]
  [173 140 107]
  [177 144 111]
  ...
  [187 154 121]
  [183 149 112]
  [200 166 129]]

 ...

 [[149 124  94]
  [161 136 106]
  [159 132 103]
  ...
  [165 131  94]
  [199 165 128]
  [200 165 127]]

 [[155 130 100]
  [156 131 101]
  [163 136 107]
  ...
  [188 154 117]
  [198 164 127]
  [204 169 131]]

 [[169 144 114]
  [173 146 117]
  [167 140 111]
  ...
  [206 172 134]
  [210 176 138]
  [197 163 125]]]
270 
 [[[ 34  50  37]
  [ 43  59  46]
  [ 43  60  42]
  ...
  [128 126 114]
  [136 131 125]
  [136 131 125]]

 [[ 32  53  38]
  [ 34  55  40]
  [ 35  56  37]
  ...
  [129 127 115]
  [133 128 122]
  [135 130 124]]

 [[ 32  53  34]
  [ 31  52  33]
  [ 30  51  32]
  ...
  [136 131 125]
  [128 124 113]
  [132 128 117]]

 ...

 [[ 66  70  79]
  [ 71  75  84]
  [ 45  

400 
 [[[171 135 121]
  [161  96  78]
  [141  86  66]
  ...
  [193 186 193]
  [187 182 188]
  [188 183 189]]

 [[155 123 108]
  [190 129 110]
  [157  96  78]
  ...
  [186 175 183]
  [191 181 189]
  [187 177 185]]

 [[161 133 130]
  [161 102  84]
  [136  81  60]
  ...
  [192 181 189]
  [192 181 189]
  [197 186 194]]

 ...

 [[174 142 119]
  [167 135 112]
  [193 163 139]
  ...
  [119 124 128]
  [118 123 127]
  [125 130 134]]

 [[171 140 112]
  [156 125  97]
  [180 143 124]
  ...
  [134 139 145]
  [123 128 134]
  [121 126 132]]

 [[199 166 147]
  [188 155 136]
  [174 147 118]
  ...
  [117 122 128]
  [123 128 134]
  [110 115 121]]]
410 
 [[[177 157 133]
  [178 158 134]
  [185 154 125]
  ...
  [ 60  43  35]
  [ 69  52  44]
  [ 52  35  27]]

 [[176 156 132]
  [177 157 133]
  [181 157 129]
  ...
  [ 60  43  35]
  [ 59  42  34]
  [ 55  38  30]]

 [[173 155 131]
  [175 157 133]
  [176 156 131]
  ...
  [ 58  41  33]
  [ 67  49  39]
  [ 76  58  48]]

 ...

 [[159  93  97]
  [192  77  80]
  [179  

530 
 [[[255 255 255]
  [255 255 255]
  [123  98  76]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 252 251]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[136 134 137]
  [148 146 149]
  [142 140 141]
  ...
  [192 187 168]
  [172 167 148]
  [193 188 169]]

 [[151 149 150]
  [148 146 147]
  [141 140 136]
  ...
  [178 173 154]
  [202 197 178]
  [186 181 162]]

 [[136 134 135]
  [152 150 151]
  [165 164 160]
  ...
  [190 185 166]
  [196 191 172]
  [211 206 187]]]
540 
 [[[175 176 162]
  [174 175 161]
  [172 173 159]
  ...
  [182 180 167]
  [180 180 168]
  [186 186 174]]

 [[159 160 146]
  [152 153 139]
  [148 149 135]
  ...
  [213 213 203]
  [211 212 204]
  [211 212 204]]

 [[194 192 180]
  [196 194 182]
  [193 194 180]
  ...
  [229 227 215]
  [224 225 211]
  [221 221 213]]

 ...

 [[138 136 121]
  [174 175 161]
  [153 1

670 
 [[[154 184 212]
  [155 185 213]
  [157 187 215]
  ...
  [152 177 199]
  [158 180 203]
  [161 183 206]]

 [[154 184 212]
  [154 184 212]
  [156 186 214]
  ...
  [154 179 201]
  [161 183 206]
  [159 181 204]]

 [[156 186 214]
  [155 185 213]
  [157 187 215]
  ...
  [156 178 201]
  [156 178 202]
  [156 178 202]]

 ...

 [[ 97 101 110]
  [112 116 125]
  [101 105 114]
  ...
  [ 67  80  89]
  [ 67  80  89]
  [ 59  72  81]]

 [[175 166 151]
  [208 199 184]
  [203 194 179]
  ...
  [215 206 189]
  [179 169 157]
  [200 190 181]]

 [[186 177 162]
  [200 191 176]
  [190 181 166]
  ...
  [184 174 162]
  [176 166 154]
  [171 161 152]]]
680 
 [[[154 184 212]
  [155 185 213]
  [157 187 215]
  ...
  [152 177 199]
  [158 180 203]
  [161 183 206]]

 [[154 184 212]
  [154 184 212]
  [156 186 214]
  ...
  [154 179 201]
  [161 183 206]
  [159 181 204]]

 [[156 186 214]
  [155 185 213]
  [157 187 215]
  ...
  [156 178 201]
  [156 178 202]
  [156 178 202]]

 ...

 [[ 97 101 110]
  [112 116 125]
  [101 1

800 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
810 
 [[[255 159 145]
  [255 160 146]
  [255 162 147]
  ...
  [254 147 137]
  [252 142 125]
  [255 135 122]]

 [[255 159 145]
  [255 159 145]
  [254 158 144]
  ...
  [255 152 145]
  [253 146 128]
  [254 136 122]]

 [[255 158 142]
  [255 158 142]
  [254 157 141]
  ...
  [254 153 141]
  [254 148 135]
  [253 140 122]]

 ...

 [[205 204 210]
  [201 200 206]
  [205 2

940 
 [[[242 241 237]
  [206 201 198]
  [185 184 179]
  ...
  [180 179 175]
  [187 186 181]
  [198 197 192]]

 [[146 142 131]
  [148 139 130]
  [185 181 172]
  ...
  [205 204 200]
  [209 208 206]
  [201 200 198]]

 [[148 141 131]
  [164 158 146]
  [146 140 124]
  ...
  [204 201 196]
  [189 188 183]
  [199 198 193]]

 ...

 [[189 173 160]
  [173 157 144]
  [174 160 147]
  ...
  [178 165 149]
  [158 146 132]
  [212 204 193]]

 [[175 159 146]
  [180 164 151]
  [170 156 143]
  ...
  [182 169 153]
  [176 162 151]
  [199 189 177]]

 [[200 184 171]
  [188 172 159]
  [184 170 157]
  ...
  [160 147 131]
  [149 136 120]
  [200 191 174]]]
950 
 [[[ 64  78  53]
  [ 83  98  69]
  [163 173 175]
  ...
  [155 137 125]
  [159 141 127]
  [160 142 128]]

 [[229 243 226]
  [ 98 110 106]
  [105 126  83]
  ...
  [157 139 127]
  [159 141 127]
  [160 142 128]]

 [[ 68  82  82]
  [104 112  71]
  [140 152 148]
  ...
  [156 138 126]
  [162 144 130]
  [171 153 139]]

 ...

 [[115  95  84]
  [ 23  18  15]
  [ 88  

70 
 [[[255 254 253]
  [255 254 253]
  [251 251 249]
  ...
  [128 124 113]
  [ 94  87  69]
  [237 232 229]]

 [[223 212 208]
  [136 125 121]
  [231 232 226]
  ...
  [151 151 139]
  [105 102  85]
  [247 244 253]]

 [[249 241 238]
  [232 228 225]
  [224 223 221]
  ...
  [109 103  91]
  [147 139 126]
  [231 232 237]]

 ...

 [[212 202 210]
  [236 226 234]
  [244 233 241]
  ...
  [194 180 179]
  [240 226 225]
  [205 191 190]]

 [[227 216 224]
  [216 205 213]
  [227 217 225]
  ...
  [224 210 209]
  [212 198 197]
  [196 182 181]]

 [[228 217 225]
  [242 231 239]
  [235 225 233]
  ...
  [219 205 204]
  [200 186 185]
  [223 209 208]]]
80 
 [[[ 89  42  26]
  [  7   0   0]
  [  9   7   8]
  ...
  [130 101  71]
  [ 45  23  12]
  [ 59   0  16]]

 [[ 28  19  12]
  [ 89  40  33]
  [ 57  49  46]
  ...
  [ 45  28  18]
  [ 93  41  43]
  [ 80  46  60]]

 [[113 100  84]
  [ 98  73  53]
  [ 38  24  23]
  ...
  [ 21  18   9]
  [226 183 174]
  [ 69  43  46]]

 ...

 [[ 25  20  24]
  [108 137 143]
  [  2   8

200 
 [[[255 223 118]
  [255 223 118]
  [255 223 118]
  ...
  [255 223 118]
  [255 223 118]
  [255 223 118]]

 [[255 223 118]
  [255 223 118]
  [255 223 118]
  ...
  [255 223 118]
  [255 223 118]
  [255 223 118]]

 [[255 223 118]
  [255 223 118]
  [255 223 118]
  ...
  [255 223 118]
  [255 223 118]
  [255 223 118]]

 ...

 [[255 223 118]
  [255 223 118]
  [255 223 118]
  ...
  [255 223 118]
  [255 223 118]
  [255 223 118]]

 [[255 223 118]
  [255 223 118]
  [255 223 118]
  ...
  [255 223 118]
  [255 223 118]
  [255 223 118]]

 [[255 223 118]
  [255 223 118]
  [255 223 118]
  ...
  [255 223 118]
  [255 223 118]
  [255 223 118]]]
210 
 [[[178 174 163]
  [181 177 166]
  [184 180 169]
  ...
  [ 62  45  25]
  [ 63  46  28]
  [ 66  49  31]]

 [[179 175 164]
  [182 178 167]
  [184 180 169]
  ...
  [ 64  47  27]
  [ 68  51  33]
  [ 69  52  34]]

 [[181 177 166]
  [183 179 168]
  [185 181 170]
  ...
  [ 64  47  27]
  [ 69  53  30]
  [ 70  54  31]]

 ...

 [[ 92  87  83]
  [ 84  79  75]
  [101  

330 
 [[[ 45 114 143]
  [ 47 113 139]
  [ 51 121 147]
  ...
  [ 79  89  88]
  [ 81  90  85]
  [ 86  99  81]]

 [[ 77 131 141]
  [ 82 147 175]
  [ 57 127 153]
  ...
  [107 116 111]
  [114 126 116]
  [ 82  87  81]]

 [[154 141 122]
  [ 70  95  92]
  [ 45 120 151]
  ...
  [113 110  79]
  [133 138 118]
  [157 153 128]]

 ...

 [[173 189 222]
  [149 162 194]
  [176 191 224]
  ...
  [ 67  82 121]
  [106 120 157]
  [159 176 220]]

 [[228 233 236]
  [202 216 219]
  [246 250 251]
  ...
  [121 137 170]
  [ 40  54  99]
  [ 63  77 122]]

 [[239 242 233]
  [183 199 232]
  [242 252 244]
  ...
  [104 121 173]
  [ 88 102 147]
  [ 73  87 132]]]
340 
 [[[238 237 232]
  [237 236 231]
  [235 234 230]
  ...
  [230 231 225]
  [230 231 225]
  [228 229 223]]

 [[237 236 231]
  [237 236 231]
  [235 234 230]
  ...
  [230 231 225]
  [229 230 224]
  [227 228 222]]

 [[236 235 230]
  [236 235 230]
  [235 234 229]
  ...
  [227 228 222]
  [227 228 222]
  [227 228 222]]

 ...

 [[206 203 198]
  [206 203 198]
  [205 2

470 
 [[[119 106  87]
  [116 103  84]
  [106  94  78]
  ...
  [211 236 243]
  [211 236 241]
  [ 30  46  61]]

 [[106  94  82]
  [105  93  81]
  [ 99  91  78]
  ...
  [ 34  49  56]
  [ 33  49  49]
  [ 49  66  76]]

 [[105  93  79]
  [103  91  77]
  [ 98  88  76]
  ...
  [ 32  47  54]
  [ 34  47  55]
  [ 34  47  55]]

 ...

 [[ 63  65  54]
  [ 73  74  68]
  [ 47  48  42]
  ...
  [ 98  86  70]
  [184 154 120]
  [108  84  60]]

 [[ 39  40  34]
  [ 65  66  60]
  [ 60  62  51]
  ...
  [124 125 111]
  [175 145 117]
  [151 115  81]]

 [[ 43  44  38]
  [ 41  42  36]
  [ 64  66  55]
  ...
  [146 146 136]
  [104 105  97]
  [ 30  26  14]]]
480 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

 [[[191 204 221]
  [190 203 220]
  [188 204 220]
  ...
  [151 172 193]
  [155 176 195]
  [163 184 203]]

 [[192 209 225]
  [198 215 231]
  [202 218 234]
  ...
  [149 170 191]
  [154 175 194]
  [153 174 193]]

 [[202 215 232]
  [198 211 228]
  [196 212 228]
  ...
  [163 181 201]
  [166 184 204]
  [174 192 212]]

 ...

 [[174 157 139]
  [164 147 129]
  [142 125 105]
  ...
  [110  95  74]
  [167 150 130]
  [151 134 114]]

 [[161 144 126]
  [151 134 116]
  [170 153 135]
  ...
  [156 139 121]
  [176 159 141]
  [151 134 116]]

 [[109  92  74]
  [167 150 132]
  [124 107  89]
  ...
  [182 165 147]
  [129 112  94]
  [149 132 114]]]
610 
 [[[ 55  36   4]
  [ 74  48  25]
  [ 93  75  51]
  ...
  [142  83  39]
  [152  89  46]
  [150  88  47]]

 [[ 67  40  21]
  [ 82  49  40]
  [175 150 120]
  ...
  [142  83  43]
  [156  93  52]
  [142  80  43]]

 [[ 90  72  48]
  [ 77  44  29]
  [ 96  69  39]
  ...
  [140  81  41]
  [148  85  44]
  [147  88  48]]

 ...

 [[219 224 230]
  [100 112 128]
  [137 162 18

730 
 [[[233 227 215]
  [234 228 216]
  [237 230 224]
  ...
  [245 244 240]
  [248 244 241]
  [243 239 236]]

 [[234 228 216]
  [235 229 217]
  [237 230 224]
  ...
  [247 242 239]
  [250 243 237]
  [241 234 228]]

 [[233 227 213]
  [237 230 220]
  [238 231 225]
  ...
  [248 243 237]
  [247 242 238]
  [246 241 237]]

 ...

 [[ 59  81   9]
  [ 63  79  17]
  [164 159 137]
  ...
  [235 228 218]
  [234 227 219]
  [237 230 222]]

 [[ 61  83  18]
  [ 55  68  12]
  [169 165 140]
  ...
  [234 227 217]
  [233 226 220]
  [233 226 220]]

 [[ 57  75  23]
  [114 115  73]
  [ 73  87   0]
  ...
  [233 226 216]
  [232 225 215]
  [234 227 217]]]
740 
 [[[195 204 201]
  [193 202 199]
  [194 200 198]
  ...
  [225 226 228]
  [225 227 226]
  [225 227 226]]

 [[201 210 207]
  [198 207 204]
  [197 203 201]
  ...
  [225 226 228]
  [225 227 226]
  [225 227 226]]

 [[201 210 207]
  [198 207 204]
  [196 205 202]
  ...
  [226 228 227]
  [226 227 229]
  [226 227 229]]

 ...

 [[192 200 203]
  [198 206 209]
  [202 2

870 
 [[[250 249 254]
  [249 248 253]
  [247 248 253]
  ...
  [246 247 249]
  [246 247 249]
  [246 247 249]]

 [[249 248 253]
  [249 248 253]
  [247 248 253]
  ...
  [246 247 249]
  [246 247 249]
  [245 246 248]]

 [[250 249 254]
  [249 248 253]
  [247 248 253]
  ...
  [246 247 249]
  [246 247 249]
  [244 248 249]]

 ...

 [[ 32  25  17]
  [ 46  31  26]
  [ 16  11   8]
  ...
  [221 214 198]
  [222 221 219]
  [235 236 241]]

 [[ 18  16  17]
  [ 31  22  17]
  [ 13  12   8]
  ...
  [215 212 197]
  [229 228 234]
  [239 240 245]]

 [[ 37  36  32]
  [ 83  73  63]
  [ 16  12   9]
  ...
  [222 219 212]
  [236 235 241]
  [239 240 245]]]
880 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [192 189 184]
  [190 189 184]
  [191 186 182]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [192 189 184]
  [189 188 183]
  [190 185 181]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [194 189 185]
  [193 188 184]
  [190 185 181]]

 ...

 [[161 160 155]
  [160 159 154]
  [158 1

In [43]:
# 학습 전용 데이터와 테스트 전용 데이터 구분 ---101
#x_train, x_test, y_train, y_test= train_test_split(x,y)
xy=(x, y)
np.save("./image/5obj.npy", xy)

print("ok,", len(y))

ValueError: could not broadcast input array from shape (5000,64,64,3) into shape (5000)

In [44]:
categories=["coat","dress","pullover","t","shirt"]
nb_classes=len(categories)
image_w=64
image_h=64

In [45]:
# ---101
#x_train, x_test, y_train, y_test = np.load("./image/5obj.npy")
#데이터 정규화하기
#x_train = x_train.astype("float")/256
x = x.astype("float")/256
#print('x_train:', x_train.shape)

In [46]:
yhat = model.predict_classes(x)

ValueError: Error when checking input: expected conv2d_1_input to have shape (28, 28, 1) but got array with shape (64, 64, 3)

In [18]:
print('accuracy: ',score[1])
print('loss: ',score[0])

accuracy:  0.9058
loss:  0.25161635910868646
